# generated by datamodel-codegen:
#   filename:  collection/collection_list_changed_webhook.json
#   timestamp: 2026-04-16T02:55:59+00:00

from __future__ import annotations

from typing import Annotated, Literal

from adcp.types.base import AdCPBaseModel
from pydantic import AwareDatetime, ConfigDict, Field

from ..core import ext as ext_1


class ChangeSummary(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    collections_added: Annotated[
        int | None, Field(description='Number of collections added since last resolution')
    ] = None
    collections_removed: Annotated[
        int | None, Field(description='Number of collections removed since last resolution')
    ] = None
    total_collections: Annotated[
        int | None, Field(description='Total collections in the resolved list')
    ] = None


class CollectionListChangedWebhook(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    event: Annotated[Literal['collection_list_changed'], Field(description='The event type')]
    list_id: Annotated[str, Field(description='ID of the collection list that changed')]
    list_name: Annotated[str | None, Field(description='Name of the collection list')] = None
    change_summary: Annotated[
        ChangeSummary | None, Field(description='Summary of changes to the resolved list')
    ] = None
    resolved_at: Annotated[AwareDatetime, Field(description='When the list was re-resolved')]
    cache_valid_until: Annotated[
        AwareDatetime | None,
        Field(description='When the consumer should refresh from the governance agent'),
    ] = None
    signature: Annotated[
        str,
        Field(
            description="Cryptographic signature of the webhook payload, signed with the agent's private key. Recipients MUST verify this signature."
        ),
    ]
    ext: ext_1.ExtensionObject | None = None
