# generated by datamodel-codegen:
#   filename:  collection/delete_collection_list_response.json
#   timestamp: 2026-04-16T02:55:59+00:00

from __future__ import annotations

from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import ConfigDict, Field

from ..core import ext as ext_1


class DeleteCollectionListResponse(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    deleted: Annotated[bool, Field(description='Whether the list was successfully deleted')]
    list_id: Annotated[str, Field(description='ID of the deleted list')]
    ext: ext_1.ExtensionObject | None = None
