# generated by datamodel-codegen:
#   filename:  collection/update_collection_list_response.json
#   timestamp: 2026-04-22T04:27:52+00:00

from __future__ import annotations

from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import ConfigDict, Field

from ..core import context as context_1
from ..core import ext as ext_1
from . import collection_list


class UpdateCollectionListResponse(AdCPBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    list: Annotated[
        collection_list.CollectionList, Field(description="The updated collection list")
    ]
    context: context_1.ContextObject | None = None
    ext: ext_1.ExtensionObject | None = None
