# generated by datamodel-codegen:
#   filename:  enums/adcp_protocol.json
#   timestamp: 2026-04-18T19:31:26+00:00

from __future__ import annotations

from enum import Enum


class AdcpProtocol(Enum):
    media_buy = 'media-buy'
    signals = 'signals'
    governance = 'governance'
    creative = 'creative'
    brand = 'brand'
    sponsored_intelligence = 'sponsored-intelligence'
