# generated by datamodel-codegen:
#   filename:  enums/adjustment_kind.json
#   timestamp: 2026-04-02T22:34:46+00:00

from __future__ import annotations

from enum import Enum


class PriceAdjustmentKind(Enum):
    fee = 'fee'
    discount = 'discount'
    commission = 'commission'
    settlement = 'settlement'
