# generated by datamodel-codegen:
#   filename:  enums/assessment_status.json
#   timestamp: 2026-04-02T22:34:46+00:00

from __future__ import annotations

from enum import Enum


class AssessmentStatus(Enum):
    insufficient = "insufficient"
    minimum = "minimum"
    good = "good"
    excellent = "excellent"
