# generated by datamodel-codegen:
#   filename:  enums/audience_status.json
#   timestamp: 2026-04-22T10:13:46+00:00

from __future__ import annotations

from enum import Enum


class AudienceStatus(Enum):
    processing = "processing"
    ready = "ready"
    too_small = "too_small"
