# generated by datamodel-codegen:
#   filename:  enums/audience_source.json
#   timestamp: 2026-04-22T04:27:52+00:00

from __future__ import annotations

from enum import Enum


class AudienceSource(Enum):
    synced = "synced"
    platform = "platform"
    third_party = "third_party"
    lookalike = "lookalike"
    retargeting = "retargeting"
    unknown = "unknown"
