# generated by datamodel-codegen:
#   filename:  enums/budget_authority_level.json
#   timestamp: 2026-03-16T00:33:16+00:00

from __future__ import annotations

from enum import Enum


class BudgetAuthorityLevel(Enum):
    agent_full = 'agent_full'
    agent_limited = 'agent_limited'
    human_required = 'human_required'
