# generated by datamodel-codegen:
#   filename:  enums/canceled_by.json
#   timestamp: 2026-04-22T04:27:52+00:00

from __future__ import annotations

from enum import Enum


class CanceledBy(Enum):
    buyer = "buyer"
    seller = "seller"
