# generated by datamodel-codegen:
#   filename:  enums/catalog_item_status.json
#   timestamp: 2026-04-22T04:27:52+00:00

from __future__ import annotations

from enum import Enum


class CatalogItemStatus(Enum):
    approved = "approved"
    pending = "pending"
    rejected = "rejected"
    warning = "warning"
