# generated by datamodel-codegen:
#   filename:  enums/cloud_storage_protocol.json
#   timestamp: 2026-04-22T04:27:52+00:00

from __future__ import annotations

from enum import Enum


class CloudStorageProtocol(Enum):
    s3 = "s3"
    gcs = "gcs"
    azure_blob = "azure_blob"
