# generated by datamodel-codegen:
#   filename:  enums/co_branding_requirement.json
#   timestamp: 2026-04-22T04:27:52+00:00

from __future__ import annotations

from enum import Enum


class CoBrandingRequirement(Enum):
    required = "required"
    optional = "optional"
    none = "none"
