# generated by datamodel-codegen:
#   filename:  enums/collection_status.json
#   timestamp: 2026-04-22T04:27:52+00:00

from __future__ import annotations

from enum import Enum


class CollectionStatus(Enum):
    active = "active"
    hiatus = "hiatus"
    ended = "ended"
    upcoming = "upcoming"
