# generated by datamodel-codegen:
#   filename:  enums/collection_cadence.json
#   timestamp: 2026-04-22T04:27:52+00:00

from __future__ import annotations

from enum import Enum


class CollectionCadence(Enum):
    daily = "daily"
    weekly = "weekly"
    monthly = "monthly"
    seasonal = "seasonal"
    event = "event"
    irregular = "irregular"
