# generated by datamodel-codegen:
#   filename:  enums/collection_relationship.json
#   timestamp: 2026-04-22T10:13:46+00:00

from __future__ import annotations

from enum import Enum


class CollectionRelationship(Enum):
    spinoff = "spinoff"
    companion = "companion"
    sequel = "sequel"
    prequel = "prequel"
    crossover = "crossover"
