# generated by datamodel-codegen:
#   filename:  enums/content_rating_system.json
#   timestamp: 2026-03-16T00:33:16+00:00

from __future__ import annotations

from enum import Enum


class ContentRatingSystem(Enum):
    tv_parental = 'tv_parental'
    mpaa = 'mpaa'
    podcast = 'podcast'
    esrb = 'esrb'
    bbfc = 'bbfc'
    fsk = 'fsk'
    acb = 'acb'
    custom = 'custom'
