# generated by datamodel-codegen:
#   filename:  enums/creative_sort_field.json
#   timestamp: 2026-03-16T00:33:16+00:00

from __future__ import annotations

from enum import Enum


class CreativeSortField(Enum):
    created_date = 'created_date'
    updated_date = 'updated_date'
    name = 'name'
    status = 'status'
    assignment_count = 'assignment_count'
