# generated by datamodel-codegen:
#   filename:  enums/creative_identifier_type.json
#   timestamp: 2026-04-22T04:27:52+00:00

from __future__ import annotations

from enum import Enum


class CreativeIdentifierType(Enum):
    ad_id = "ad_id"
    isci = "isci"
    clearcast_clock = "clearcast_clock"
