# generated by datamodel-codegen:
#   filename:  enums/creative_status.json
#   timestamp: 2026-04-02T22:34:46+00:00

from __future__ import annotations

from enum import Enum


class CreativeStatus(Enum):
    processing = "processing"
    pending_review = "pending_review"
    approved = "approved"
    rejected = "rejected"
    archived = "archived"
