# generated by datamodel-codegen:
#   filename:  enums/day_of_week.json
#   timestamp: 2026-04-22T04:27:52+00:00

from __future__ import annotations

from enum import Enum


class DayOfWeek(Enum):
    monday = "monday"
    tuesday = "tuesday"
    wednesday = "wednesday"
    thursday = "thursday"
    friday = "friday"
    saturday = "saturday"
    sunday = "sunday"
