# generated by datamodel-codegen:
#   filename:  enums/delegation_authority.json
#   timestamp: 2026-04-22T10:13:46+00:00

from __future__ import annotations

from enum import Enum


class DelegationAuthority(Enum):
    full = "full"
    execute_only = "execute_only"
    propose_only = "propose_only"
