# generated by datamodel-codegen:
#   filename:  enums/derivative_type.json
#   timestamp: 2026-03-16T00:33:16+00:00

from __future__ import annotations

from enum import Enum


class DerivativeType(Enum):
    clip = 'clip'
    highlight = 'highlight'
    recap = 'recap'
    trailer = 'trailer'
    bonus = 'bonus'
