# generated by datamodel-codegen:
#   filename:  enums/episode_status.json
#   timestamp: 2026-03-16T00:33:16+00:00

from __future__ import annotations

from enum import Enum


class EpisodeStatus(Enum):
    scheduled = 'scheduled'
    tentative = 'tentative'
    live = 'live'
    postponed = 'postponed'
    cancelled = 'cancelled'
    aired = 'aired'
    published = 'published'
