# generated by datamodel-codegen:
#   filename:  enums/escalation_severity.json
#   timestamp: 2026-04-22T10:13:46+00:00

from __future__ import annotations

from enum import Enum


class EscalationSeverity(Enum):
    info = "info"
    warning = "warning"
    critical = "critical"
