# generated by datamodel-codegen:
#   filename:  enums/escalation_severity.json
#   timestamp: 2026-03-16T00:33:16+00:00

from __future__ import annotations

from enum import Enum


class EscalationSeverity(Enum):
    info = "info"
    warning = "warning"
    critical = "critical"
