# generated by datamodel-codegen:
#   filename:  enums/exclusivity.json
#   timestamp: 2026-03-16T00:33:16+00:00

from __future__ import annotations

from enum import Enum


class Exclusivity(Enum):
    none = 'none'
    category = 'category'
    exclusive = 'exclusive'
