# generated by datamodel-codegen:
#   filename:  enums/forecast_method.json
#   timestamp: 2026-04-22T04:27:52+00:00

from __future__ import annotations

from enum import Enum


class ForecastMethod(Enum):
    estimate = "estimate"
    modeled = "modeled"
    guaranteed = "guaranteed"
