# generated by datamodel-codegen:
#   filename:  enums/forecast_range_unit.json
#   timestamp: 2026-04-22T10:13:46+00:00

from __future__ import annotations

from enum import Enum


class ForecastRangeUnit(Enum):
    spend = "spend"
    availability = "availability"
    reach_freq = "reach_freq"
    weekly = "weekly"
    daily = "daily"
    clicks = "clicks"
    conversions = "conversions"
    package = "package"
