# generated by datamodel-codegen:
#   filename:  enums/governance_mode.json
#   timestamp: 2026-03-16T00:33:16+00:00

from __future__ import annotations

from enum import Enum


class GovernanceMode(Enum):
    audit = "audit"
    advisory = "advisory"
    enforce = "enforce"
