# generated by datamodel-codegen:
#   filename:  enums/governance_phase.json
#   timestamp: 2026-04-19T21:22:45+00:00

from __future__ import annotations

from enum import Enum


class GovernancePhase(Enum):
    purchase = "purchase"
    modification = "modification"
    delivery = "delivery"
