# generated by datamodel-codegen:
#   filename:  enums/governance_domain.json
#   timestamp: 2026-04-22T04:27:52+00:00

from __future__ import annotations

from enum import Enum


class GovernanceDomain(Enum):
    campaign = "campaign"
    property = "property"
    creative = "creative"
    content_standards = "content_standards"
