# generated by datamodel-codegen:
#   filename:  enums/installment_status.json
#   timestamp: 2026-04-21T22:41:55+00:00

from __future__ import annotations

from enum import Enum


class InstallmentStatus(Enum):
    scheduled = "scheduled"
    tentative = "tentative"
    live = "live"
    postponed = "postponed"
    cancelled = "cancelled"
    aired = "aired"
    published = "published"
