# generated by datamodel-codegen:
#   filename:  enums/makegood_remedy.json
#   timestamp: 2026-04-22T04:27:52+00:00

from __future__ import annotations

from enum import Enum


class MakegoodRemedy(Enum):
    additional_delivery = "additional_delivery"
    credit = "credit"
    invoice_adjustment = "invoice_adjustment"
