# generated by datamodel-codegen:
#   filename:  enums/match_id_type.json
#   timestamp: 2026-04-22T04:27:52+00:00

from __future__ import annotations

from enum import Enum


class MatchIdType(Enum):
    hashed_email = "hashed_email"
    hashed_phone = "hashed_phone"
    rampid = "rampid"
    id5 = "id5"
    uid2 = "uid2"
    euid = "euid"
    pairid = "pairid"
    maid = "maid"
    other = "other"
