# generated by datamodel-codegen:
#   filename:  enums/notification_type.json
#   timestamp: 2026-04-22T04:27:52+00:00

from __future__ import annotations

from enum import Enum


class NotificationType(Enum):
    scheduled = "scheduled"
    final = "final"
    delayed = "delayed"
    adjusted = "adjusted"
