# generated by datamodel-codegen:
#   filename:  enums/outcome_type.json
#   timestamp: 2026-03-16T00:33:16+00:00

from __future__ import annotations

from enum import Enum


class OutcomeType(Enum):
    completed = 'completed'
    failed = 'failed'
    delivery = 'delivery'
