# generated by datamodel-codegen:
#   filename:  enums/performance_standard_metric.json
#   timestamp: 2026-04-22T10:13:46+00:00

from __future__ import annotations

from enum import Enum


class PerformanceStandardMetric(Enum):
    viewability = "viewability"
    ivt = "ivt"
    completion_rate = "completion_rate"
    brand_safety = "brand_safety"
    attention_score = "attention_score"
