# generated by datamodel-codegen:
#   filename:  enums/policy_enforcement.json
#   timestamp: 2026-03-16T00:33:16+00:00

from __future__ import annotations

from enum import Enum


class PolicyEnforcementLevel(Enum):
    must = "must"
    should = "should"
    may = "may"
