# generated by datamodel-codegen:
#   filename:  enums/publisher_identifier_types.json
#   timestamp: 2026-04-22T04:27:52+00:00

from __future__ import annotations

from enum import Enum


class PublisherIdentifierTypes(Enum):
    tag_id = "tag_id"
    duns = "duns"
    lei = "lei"
    seller_id = "seller_id"
    gln = "gln"
