# generated by datamodel-codegen:
#   filename:  enums/purchase_type.json
#   timestamp: 2026-04-18T19:31:26+00:00

from __future__ import annotations

from enum import Enum


class PurchaseType(Enum):
    media_buy = 'media_buy'
    rights_license = 'rights_license'
    signal_activation = 'signal_activation'
    creative_services = 'creative_services'
