# generated by datamodel-codegen:
#   filename:  enums/reporting_frequency.json
#   timestamp: 2026-04-22T10:13:46+00:00

from __future__ import annotations

from enum import Enum


class ReportingFrequency(Enum):
    hourly = "hourly"
    daily = "daily"
    monthly = "monthly"
