# generated by datamodel-codegen:
#   filename:  enums/response_type.json
#   timestamp: 2026-04-22T04:27:52+00:00

from __future__ import annotations

from enum import Enum


class TmpResponseType(Enum):
    activation = "activation"
    catalog_items = "catalog_items"
    creative = "creative"
    deal = "deal"
