# generated by datamodel-codegen:
#   filename:  enums/right_use.json
#   timestamp: 2026-03-16T00:33:16+00:00

from __future__ import annotations

from enum import Enum


class RightUse(Enum):
    likeness = 'likeness'
    voice = 'voice'
    name = 'name'
    endorsement = 'endorsement'
    motion_capture = 'motion_capture'
    signature = 'signature'
    catchphrase = 'catchphrase'
    sync = 'sync'
    background_music = 'background_music'
    editorial = 'editorial'
    commercial = 'commercial'
