# generated by datamodel-codegen:
#   filename:  enums/show_relationship.json
#   timestamp: 2026-03-16T00:33:16+00:00

from __future__ import annotations

from enum import Enum


class ShowRelationship(Enum):
    spinoff = 'spinoff'
    companion = 'companion'
    sequel = 'sequel'
    prequel = 'prequel'
    crossover = 'crossover'
