# generated by datamodel-codegen:
#   filename:  enums/show_status.json
#   timestamp: 2026-03-16T00:33:16+00:00

from __future__ import annotations

from enum import Enum


class ShowStatus(Enum):
    active = 'active'
    hiatus = 'hiatus'
    ended = 'ended'
    upcoming = 'upcoming'
