# generated by datamodel-codegen:
#   filename:  enums/show_cadence.json
#   timestamp: 2026-03-16T00:33:16+00:00

from __future__ import annotations

from enum import Enum


class ShowCadence(Enum):
    daily = 'daily'
    weekly = 'weekly'
    seasonal = 'seasonal'
    event = 'event'
    irregular = 'irregular'
