# generated by datamodel-codegen:
#   filename:  enums/si_session_status.json
#   timestamp: 2026-04-22T04:27:52+00:00

from __future__ import annotations

from enum import Enum


class SiSessionStatus(Enum):
    active = "active"
    pending_handoff = "pending_handoff"
    complete = "complete"
    terminated = "terminated"
