# generated by datamodel-codegen:
#   filename:  enums/signal_source.json
#   timestamp: 2026-04-22T04:27:52+00:00

from __future__ import annotations

from enum import Enum


class SignalSource(Enum):
    catalog = "catalog"
    agent = "agent"
