# generated by datamodel-codegen:
#   filename:  enums/sort_direction.json
#   timestamp: 2026-04-21T22:41:55+00:00

from __future__ import annotations

from enum import Enum


class SortDirection(Enum):
    asc = "asc"
    desc = "desc"
