# generated by datamodel-codegen:
#   filename:  enums/special_category.json
#   timestamp: 2026-04-21T22:41:55+00:00

from __future__ import annotations

from enum import Enum


class SpecialCategory(Enum):
    awards = "awards"
    championship = "championship"
    concert = "concert"
    conference = "conference"
    election = "election"
    festival = "festival"
    gala = "gala"
    holiday = "holiday"
    premiere = "premiere"
    product_launch = "product_launch"
    reunion = "reunion"
    tribute = "tribute"
