# generated by datamodel-codegen:
#   filename:  enums/talent_role.json
#   timestamp: 2026-03-16T00:33:16+00:00

from __future__ import annotations

from enum import Enum


class TalentRole(Enum):
    host = 'host'
    guest = 'guest'
    creator = 'creator'
    cast = 'cast'
    narrator = 'narrator'
    producer = 'producer'
    correspondent = 'correspondent'
