# generated by datamodel-codegen:
#   filename:  enums/viewability_standard.json
#   timestamp: 2026-04-16T02:55:59+00:00

from __future__ import annotations

from enum import Enum


class ViewabilityStandard(Enum):
    mrc = 'mrc'
    groupm = 'groupm'
