# generated by datamodel-codegen:
#   filename:  enums/viewability_standard.json
#   timestamp: 2026-04-22T04:27:52+00:00

from __future__ import annotations

from enum import Enum


class ViewabilityStandard(Enum):
    mrc = "mrc"
    groupm = "groupm"
