# generated by datamodel-codegen:
#   filename:  bundled/media_buy/get_media_buys_response.json
#   timestamp: 2026-04-18T19:31:26+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from adcp.types.base import AdCPBaseModel
from pydantic import AnyUrl, AwareDatetime, ConfigDict, EmailStr, Field, RootModel


class Status(Enum):
    active = 'active'
    pending_approval = 'pending_approval'
    rejected = 'rejected'
    payment_required = 'payment_required'
    suspended = 'suspended'
    closed = 'closed'


class Brand(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    domain: Annotated[
        str,
        Field(
            description="Domain where /.well-known/brand.json is hosted, or the brand's operating domain",
            pattern='^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)*$',
        ),
    ]
    brand_id: Annotated[
        str | None,
        Field(
            description='Brand identifier within the house portfolio. Optional for single-brand domains.',
            examples=['tide', 'cheerios', 'air_jordan', 'nike', 'pampers'],
            pattern='^[a-z0-9_]+$',
            title='Brand ID',
        ),
    ] = None


class Billing(Enum):
    operator = 'operator'
    agent = 'agent'
    advertiser = 'advertiser'


class Address(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    street: Annotated[
        str, Field(description='Street address including building number', max_length=200)
    ]
    city: Annotated[str, Field(max_length=100)]
    postal_code: Annotated[str, Field(max_length=20)]
    region: Annotated[
        str | None, Field(description='State, province, or region', max_length=100)
    ] = None
    country: Annotated[
        str, Field(description='ISO 3166-1 alpha-2 country code', pattern='^[A-Z]{2}$')
    ]


class Role(Enum):
    billing = 'billing'
    legal = 'legal'
    creative = 'creative'
    general = 'general'


class Contact(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    role: Annotated[
        Role, Field(description="Contact's functional role in the business relationship")
    ]
    name: Annotated[str | None, Field(description='Full name of the contact', max_length=200)] = (
        None
    )
    email: Annotated[EmailStr | None, Field(max_length=254)] = None
    phone: Annotated[str | None, Field(max_length=30)] = None


class Bank(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    account_holder: Annotated[str, Field(description='Name on the bank account', max_length=200)]
    iban: Annotated[
        str | None,
        Field(
            description='International Bank Account Number (SEPA markets)',
            pattern='^[A-Z]{2}[0-9]{2}[A-Z0-9]{4,30}$',
        ),
    ] = None
    bic: Annotated[
        str | None,
        Field(
            description='Bank Identifier Code / SWIFT code (SEPA markets)',
            pattern='^[A-Z]{4}[A-Z]{2}[A-Z0-9]{2}([A-Z0-9]{3})?$',
        ),
    ] = None
    routing_number: Annotated[
        str | None,
        Field(
            description='Bank routing number for non-SEPA markets (e.g., US ABA routing number, Canadian transit/institution number)',
            max_length=30,
        ),
    ] = None
    account_number: Annotated[
        str | None, Field(description='Bank account number for non-SEPA markets', max_length=30)
    ] = None


class BillingEntity(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    legal_name: Annotated[
        str, Field(description='Registered legal name of the business entity', max_length=200)
    ]
    vat_id: Annotated[
        str | None,
        Field(
            description='VAT identification number (e.g., DE123456789 for Germany, FR12345678901 for France). Required for B2B invoicing in the EU. Must be normalized: no spaces, dots, or dashes.',
            pattern='^[A-Z]{2}[A-Z0-9]{2,13}$',
        ),
    ] = None
    tax_id: Annotated[
        str | None,
        Field(
            description='Tax identification number for jurisdictions that do not use VAT (e.g., US EIN)',
            max_length=30,
        ),
    ] = None
    registration_number: Annotated[
        str | None,
        Field(
            description='Company registration number (e.g., HRB 12345 for German Handelsregister)',
            max_length=50,
        ),
    ] = None
    address: Annotated[
        Address | None, Field(description='Postal address for invoicing and legal correspondence')
    ] = None
    contacts: Annotated[
        list[Contact] | None,
        Field(
            description='Contacts for billing, legal, and operational matters. Contains personal data subject to GDPR and equivalent regulations. Implementations MUST use this data only for invoicing and account management.',
            max_length=10,
        ),
    ] = None
    bank: Annotated[
        Bank | None,
        Field(
            description='Bank account details for payment processing. Write-only: included in requests to provide payment coordinates, but MUST NOT be echoed in responses. Sellers store these details and confirm receipt without returning them.'
        ),
    ] = None
    ext: Annotated[
        dict[str, Any] | None,
        Field(
            description='Extension object for platform-specific, vendor-namespaced parameters. Extensions are always optional and must be namespaced under a vendor/platform key (e.g., ext.gam, ext.roku). Used for custom capabilities, partner-specific configuration, and features being proposed for standardization.',
            title='Extension Object',
        ),
    ] = None


class PaymentTerms(Enum):
    net_15 = 'net_15'
    net_30 = 'net_30'
    net_45 = 'net_45'
    net_60 = 'net_60'
    net_90 = 'net_90'
    prepay = 'prepay'


class CreditLimit(AdCPBaseModel):
    amount: Annotated[float, Field(ge=0.0)]
    currency: Annotated[str, Field(pattern='^[A-Z]{3}$')]


class Setup(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    url: Annotated[
        AnyUrl | None,
        Field(
            description='URL where the human can complete the required action (credit application, legal agreement, add funds).'
        ),
    ] = None
    message: Annotated[str, Field(description="Human-readable description of what's needed.")]
    expires_at: Annotated[
        AwareDatetime | None, Field(description='When this setup link expires.')
    ] = None


class AccountScope(Enum):
    operator = 'operator'
    brand = 'brand'
    operator_brand = 'operator_brand'
    agent = 'agent'


class Category(RootModel[str]):
    root: Annotated[str, Field(max_length=64, pattern='^[a-z][a-z0-9_]*$')]


class GovernanceAgent(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    url: Annotated[AnyUrl, Field(description='Governance agent endpoint URL. Must use HTTPS.')]
    categories: Annotated[
        list[Category] | None,
        Field(
            description="Governance categories this agent handles (e.g., ['budget_authority', 'strategic_alignment']). When omitted, the agent handles all categories.",
            max_length=20,
        ),
    ] = None


class Protocol(Enum):
    s3 = 's3'
    gcs = 'gcs'
    azure_blob = 'azure_blob'


class Format(Enum):
    jsonl = 'jsonl'
    csv = 'csv'
    parquet = 'parquet'
    avro = 'avro'
    orc = 'orc'


class Compression(Enum):
    gzip = 'gzip'
    none = 'none'


class ReportingBucket(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocol: Annotated[
        Protocol, Field(description='Cloud storage protocol', title='Cloud Storage Protocol')
    ]
    bucket: Annotated[
        str,
        Field(
            description='Bucket or container name',
            max_length=63,
            min_length=3,
            pattern='^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$',
        ),
    ]
    prefix: Annotated[
        str | None,
        Field(
            description='Path prefix within the bucket. Seller appends date-based partitioning beneath this prefix.',
            examples=['accounts/pinnacle/adcp', 'reporting/2024'],
            max_length=512,
            pattern='^[a-zA-Z0-9/_.-]+$',
        ),
    ] = None
    region: Annotated[
        str | None,
        Field(
            description='Cloud region for the bucket',
            examples=['us-east-1', 'europe-west1'],
            max_length=64,
            pattern='^[a-z0-9-]+$',
        ),
    ] = None
    format: Annotated[
        Format | None,
        Field(
            description='File format for delivered files. Parquet, Avro, and ORC use internal compression (the top-level compression field is ignored for these formats).'
        ),
    ] = Format.jsonl
    compression: Annotated[
        Compression | None, Field(description='Compression applied to delivered files')
    ] = Compression.gzip
    file_retention_days: Annotated[
        int,
        Field(
            description='How long reporting files are retained in the bucket before deletion. Buyers must read files within this window. Minimum recommended: 14 days.',
            examples=[14, 30, 90],
            ge=1,
        ),
    ]
    setup_instructions: Annotated[
        AnyUrl | None,
        Field(
            description='URL to documentation for configuring buyer read access to this bucket (IAM role, service account, etc.). Operator-facing documentation — buyer agents MUST NOT auto-fetch this URL; surface it to a human operator. If an implementation fetches it (for preview), apply webhook URL SSRF validation and do not pass the fetched content into an LLM context without indirect-prompt-injection guarding. See docs/media-buy/media-buys/optimization-reporting#security-considerations-for-offline-delivery.'
        ),
    ] = None


class Account(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    account_id: Annotated[str, Field(description='Unique identifier for this account')]
    name: Annotated[
        str, Field(description="Human-readable account name (e.g., 'Acme', 'Acme c/o Pinnacle')")
    ]
    advertiser: Annotated[
        str | None, Field(description='The advertiser whose rates apply to this account')
    ] = None
    billing_proxy: Annotated[
        str | None,
        Field(
            description='Optional intermediary who receives invoices on behalf of the advertiser (e.g., agency)'
        ),
    ] = None
    status: Annotated[
        Status,
        Field(
            description='Account lifecycle status. See the Accounts Protocol overview for the operations matrix showing which tasks are permitted in each state.',
            title='Account Status',
        ),
    ]
    brand: Annotated[
        Brand | None,
        Field(
            description='Brand reference identifying the advertiser',
            examples=[
                {'domain': 'nova-brands.com', 'brand_id': 'spark'},
                {'domain': 'nova-brands.com', 'brand_id': 'glow'},
                {'domain': 'acme-corp.com'},
            ],
            title='Brand Reference',
        ),
    ] = None
    operator: Annotated[
        str | None,
        Field(
            description="Domain of the entity operating this account. When the brand operates directly, this is the brand's domain.",
            pattern='^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)*$',
        ),
    ] = None
    billing: Annotated[
        Billing | None,
        Field(
            description="Who is invoiced on this account. operator: seller invoices the operator (agency or brand buying direct). agent: agent consolidates billing. advertiser: seller invoices the advertiser directly, even when a different operator places orders on their behalf. See billing_entity for the invoiced party's business details."
        ),
    ] = None
    billing_entity: Annotated[
        BillingEntity | None,
        Field(
            description='Business entity details for the party responsible for payment. Contains the legal name, tax IDs, address, and bank details needed for formal B2B invoicing. Corresponds to whoever billing points to (operator, agent, or advertiser). When this account appears in a response, bank details MUST be omitted (write-only).',
            examples=[
                {
                    'description': 'German agency with full B2B details',
                    'data': {
                        'legal_name': 'Pinnacle Media GmbH',
                        'vat_id': 'DE123456789',
                        'registration_number': 'HRB 12345',
                        'address': {
                            'street': 'Friedrichstrasse 100',
                            'city': 'Berlin',
                            'postal_code': '10117',
                            'country': 'DE',
                        },
                        'contacts': [
                            {
                                'role': 'billing',
                                'name': 'Sam Adeyemi',
                                'email': 'billing@pinnacle-media.com',
                                'phone': '+49 30 12345678',
                            }
                        ],
                        'bank': {
                            'account_holder': 'Pinnacle Media GmbH',
                            'iban': 'DE89370400440532013000',
                            'bic': 'COBADEFFXXX',
                        },
                    },
                },
                {
                    'description': 'US advertiser with EIN and domestic bank details',
                    'data': {
                        'legal_name': 'Acme Corporation',
                        'tax_id': '12-3456789',
                        'address': {
                            'street': '123 Main St',
                            'city': 'New York',
                            'postal_code': '10001',
                            'region': 'NY',
                            'country': 'US',
                        },
                        'contacts': [
                            {
                                'role': 'billing',
                                'name': 'AP Department',
                                'email': 'ap@acme-corp.com',
                            }
                        ],
                        'bank': {
                            'account_holder': 'Acme Corporation',
                            'routing_number': '021000021',
                            'account_number': '123456789',
                        },
                    },
                },
            ],
            title='Business Entity',
        ),
    ] = None
    rate_card: Annotated[
        str | None, Field(description='Identifier for the rate card applied to this account')
    ] = None
    payment_terms: Annotated[
        PaymentTerms | None,
        Field(
            description='Payment terms agreed for this account. Binding for all invoices when the account is active.'
        ),
    ] = None
    credit_limit: Annotated[
        CreditLimit | None, Field(description='Maximum outstanding balance allowed')
    ] = None
    setup: Annotated[
        Setup | None,
        Field(
            description="Present when status is 'pending_approval'. Contains next steps for completing account activation."
        ),
    ] = None
    account_scope: Annotated[
        AccountScope | None,
        Field(
            description="How the seller scoped this account. operator: shared across all brands for this operator. brand: shared across all operators for this brand. operator_brand: dedicated to a specific operator+brand combination. agent: the agent's default account with no brand or operator association."
        ),
    ] = None
    governance_agents: Annotated[
        list[GovernanceAgent] | None,
        Field(
            description='Governance agent endpoints registered on this account. Authentication credentials are write-only and not included in responses — use sync_governance to set or update credentials.',
            max_length=10,
        ),
    ] = None
    reporting_bucket: Annotated[
        ReportingBucket | None,
        Field(
            description="Cloud storage bucket where the seller delivers offline reporting files for this account. Seller provisions a dedicated bucket or a per-account prefix within a shared bucket, and grants the buyer read access out-of-band. Access MUST be scoped at the IAM layer so each account can only read its own prefix — bucket-wide grants are non-compliant even with per-account prefixes. Seller MUST revoke access when the account's status transitions to inactive, suspended, or closed. See security considerations for offline delivery in docs/media-buy/media-buys/optimization-reporting. Only present when the seller supports offline delivery (reporting_delivery_methods includes 'offline' in capabilities)."
        ),
    ] = None
    sandbox: Annotated[
        bool | None,
        Field(
            description='When true, this is a sandbox account — no real platform calls, no real spend. For explicit accounts (require_operator_auth: true), sandbox accounts are pre-existing test accounts on the platform discovered via list_accounts. For implicit accounts, sandbox is part of the natural key: the same brand/operator pair can have both a production and sandbox account.'
        ),
    ] = None
    ext: Annotated[
        dict[str, Any] | None,
        Field(
            description='Extension object for platform-specific, vendor-namespaced parameters. Extensions are always optional and must be namespaced under a vendor/platform key (e.g., ext.gam, ext.roku). Used for custom capabilities, partner-specific configuration, and features being proposed for standardization.',
            title='Extension Object',
        ),
    ] = None


class Contact7(Contact):
    pass


class InvoiceRecipient(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    legal_name: Annotated[
        str, Field(description='Registered legal name of the business entity', max_length=200)
    ]
    vat_id: Annotated[
        str | None,
        Field(
            description='VAT identification number (e.g., DE123456789 for Germany, FR12345678901 for France). Required for B2B invoicing in the EU. Must be normalized: no spaces, dots, or dashes.',
            pattern='^[A-Z]{2}[A-Z0-9]{2,13}$',
        ),
    ] = None
    tax_id: Annotated[
        str | None,
        Field(
            description='Tax identification number for jurisdictions that do not use VAT (e.g., US EIN)',
            max_length=30,
        ),
    ] = None
    registration_number: Annotated[
        str | None,
        Field(
            description='Company registration number (e.g., HRB 12345 for German Handelsregister)',
            max_length=50,
        ),
    ] = None
    address: Annotated[
        Address | None, Field(description='Postal address for invoicing and legal correspondence')
    ] = None
    contacts: Annotated[
        list[Contact7] | None,
        Field(
            description='Contacts for billing, legal, and operational matters. Contains personal data subject to GDPR and equivalent regulations. Implementations MUST use this data only for invoicing and account management.',
            max_length=10,
        ),
    ] = None
    bank: Annotated[
        Bank | None,
        Field(
            description='Bank account details for payment processing. Write-only: included in requests to provide payment coordinates, but MUST NOT be echoed in responses. Sellers store these details and confirm receipt without returning them.'
        ),
    ] = None
    ext: Annotated[
        dict[str, Any] | None,
        Field(
            description='Extension object for platform-specific, vendor-namespaced parameters. Extensions are always optional and must be namespaced under a vendor/platform key (e.g., ext.gam, ext.roku). Used for custom capabilities, partner-specific configuration, and features being proposed for standardization.',
            title='Extension Object',
        ),
    ] = None


class Status11(Enum):
    pending_creatives = 'pending_creatives'
    pending_start = 'pending_start'
    active = 'active'
    paused = 'paused'
    completed = 'completed'
    rejected = 'rejected'
    canceled = 'canceled'


class CanceledBy(Enum):
    buyer = 'buyer'
    seller = 'seller'


class Cancellation(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    canceled_at: Annotated[
        AwareDatetime, Field(description='ISO 8601 timestamp when this media buy was canceled.')
    ]
    canceled_by: Annotated[
        CanceledBy,
        Field(description='Which party initiated the cancellation.', title='Canceled By'),
    ]
    reason: Annotated[
        str | None, Field(description='Reason the media buy was canceled.', max_length=500)
    ] = None


class ValidAction(Enum):
    pause = 'pause'
    resume = 'resume'
    cancel = 'cancel'
    update_budget = 'update_budget'
    update_dates = 'update_dates'
    update_packages = 'update_packages'
    add_packages = 'add_packages'
    sync_creatives = 'sync_creatives'


class HistoryItem(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    revision: Annotated[
        int, Field(description='Revision number after this change was applied.', ge=1)
    ]
    timestamp: Annotated[AwareDatetime, Field(description='When this change occurred.')]
    actor: Annotated[
        str | None,
        Field(
            description='Identity of who made the change — derived from authentication context, not caller-provided. Format is seller-defined (e.g., agent URL, user email, API key label).'
        ),
    ] = None
    action: Annotated[
        str,
        Field(
            description='What happened. Standard actions: created, activated, paused, resumed, canceled, rejected, completed, updated_budget, updated_dates, updated_packages, package_canceled, package_paused, package_resumed. Sellers MAY use additional platform-specific actions (e.g., creative_approved, targeting_updated) — use ext on the history entry for structured metadata about custom actions.'
        ),
    ]
    summary: Annotated[
        str | None,
        Field(
            description="Human-readable summary of the change (e.g., 'Budget increased from $5,000 to $7,500 on pkg_abc').",
            max_length=500,
        ),
    ] = None
    package_id: Annotated[
        str | None,
        Field(description='Package affected, when the change targeted a specific package.'),
    ] = None
    ext: Annotated[
        dict[str, Any] | None,
        Field(
            description='Extension object for platform-specific, vendor-namespaced parameters. Extensions are always optional and must be namespaced under a vendor/platform key (e.g., ext.gam, ext.roku). Used for custom capabilities, partner-specific configuration, and features being proposed for standardization.',
            title='Extension Object',
        ),
    ] = None


class Cancellation4(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    canceled_at: Annotated[
        AwareDatetime, Field(description='ISO 8601 timestamp when this package was canceled.')
    ]
    canceled_by: Annotated[
        CanceledBy,
        Field(description='Which party initiated the package cancellation.', title='Canceled By'),
    ]
    reason: Annotated[
        str | None, Field(description='Reason the package was canceled.', max_length=500)
    ] = None


class ApprovalStatus(Enum):
    pending_review = 'pending_review'
    approved = 'approved'
    rejected = 'rejected'


class CreativeApproval(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    creative_id: Annotated[str, Field(description='Creative identifier')]
    approval_status: Annotated[
        ApprovalStatus,
        Field(
            description='Approval state of a creative on a specific package',
            title='Creative Approval Status',
        ),
    ]
    rejection_reason: Annotated[
        str | None,
        Field(
            description="Human-readable explanation of why the creative was rejected. Present only when approval_status is 'rejected'."
        ),
    ] = None


class FormatIdsPendingItem(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    agent_url: Annotated[
        AnyUrl,
        Field(
            description="URL of the agent that defines this format (e.g., 'https://creatives.adcontextprotocol.org' for standard formats, or 'https://publisher.com/.well-known/adcp/sales' for custom formats)"
        ),
    ]
    id: Annotated[
        str,
        Field(
            description="Format identifier within the agent's namespace (e.g., 'display_static', 'video_hosted', 'audio_standard'). When used alone, references a template format. When combined with dimension/duration fields, creates a parameterized format ID for a specific variant.",
            pattern='^[a-zA-Z0-9_-]+$',
        ),
    ]
    width: Annotated[
        int | None,
        Field(
            description='Width in pixels for visual formats. When specified, height must also be specified. Both fields together create a parameterized format ID for dimension-specific variants.',
            ge=1,
        ),
    ] = None
    height: Annotated[
        int | None,
        Field(
            description='Height in pixels for visual formats. When specified, width must also be specified. Both fields together create a parameterized format ID for dimension-specific variants.',
            ge=1,
        ),
    ] = None
    duration_ms: Annotated[
        float | None,
        Field(
            description='Duration in milliseconds for time-based formats (video, audio). When specified, creates a parameterized format ID. Omit to reference a template format without parameters.',
            ge=1.0,
        ),
    ] = None


class SnapshotUnavailableReason(Enum):
    SNAPSHOT_UNSUPPORTED = 'SNAPSHOT_UNSUPPORTED'
    SNAPSHOT_TEMPORARILY_UNAVAILABLE = 'SNAPSHOT_TEMPORARILY_UNAVAILABLE'
    SNAPSHOT_PERMISSION_DENIED = 'SNAPSHOT_PERMISSION_DENIED'


class DeliveryStatus(Enum):
    delivering = 'delivering'
    not_delivering = 'not_delivering'
    completed = 'completed'
    budget_exhausted = 'budget_exhausted'
    flight_ended = 'flight_ended'
    goal_met = 'goal_met'


class Snapshot(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    as_of: Annotated[
        AwareDatetime,
        Field(description='ISO 8601 timestamp when this snapshot was captured by the platform'),
    ]
    staleness_seconds: Annotated[
        int,
        Field(
            description='Maximum age of this data in seconds. For example, 900 means the data may be up to 15 minutes old. Use this to interpret zero delivery: a value of 900 means zero impressions is likely real; a value of 14400 means reporting may still be catching up.',
            ge=0,
        ),
    ]
    impressions: Annotated[
        float, Field(description='Total impressions delivered since package start', ge=0.0)
    ]
    spend: Annotated[
        float,
        Field(
            description='Total spend since package start, denominated in snapshot.currency when present, otherwise package.currency or media_buy.currency',
            ge=0.0,
        ),
    ]
    currency: Annotated[
        str | None,
        Field(
            description='ISO 4217 currency code for spend in this snapshot. Optional when unchanged from package.currency or media_buy.currency.',
            pattern='^[A-Z]{3}$',
        ),
    ] = None
    clicks: Annotated[
        float | None, Field(description='Total clicks since package start (when available)', ge=0.0)
    ] = None
    pacing_index: Annotated[
        float | None,
        Field(
            description='Current delivery pace relative to expected (1.0 = on track, <1.0 = behind, >1.0 = ahead). Absent when pacing cannot be determined.',
            ge=0.0,
        ),
    ] = None
    delivery_status: Annotated[
        DeliveryStatus | None,
        Field(
            description="Operational delivery state of this package. 'not_delivering' means the package is within its scheduled flight but has delivered zero impressions for at least one full staleness cycle — the signal for automated price adjustments or buyer alerts. Implementers must not return 'not_delivering' until at least staleness_seconds have elapsed since package activation."
        ),
    ] = None
    ext: Annotated[
        dict[str, Any] | None,
        Field(
            description='Optional extension object for seller-specific snapshot fields.',
            title='Extension Object',
        ),
    ] = None


class Package(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    package_id: Annotated[str, Field(description="Seller's package identifier")]
    product_id: Annotated[
        str | None, Field(description='Product identifier this package is purchased from')
    ] = None
    budget: Annotated[
        float | None,
        Field(
            description='Package budget amount, denominated in package.currency when present, otherwise media_buy.currency',
            ge=0.0,
        ),
    ] = None
    currency: Annotated[
        str | None,
        Field(
            description='ISO 4217 currency code for monetary values at this package level (budget, bid_price, snapshot.spend). When absent, inherit media_buy.currency.',
            pattern='^[A-Z]{3}$',
        ),
    ] = None
    bid_price: Annotated[
        float | None,
        Field(
            description='Current bid price for auction-based packages. Denominated in package.currency when present, otherwise media_buy.currency. Relevant for automated price optimization loops.',
            ge=0.0,
        ),
    ] = None
    impressions: Annotated[
        float | None,
        Field(description='Goal impression count for impression-based packages', ge=0.0),
    ] = None
    start_time: Annotated[
        AwareDatetime | None,
        Field(
            description='ISO 8601 flight start time for this package. Use to determine whether the package is within its scheduled flight before interpreting delivery status.'
        ),
    ] = None
    end_time: Annotated[
        AwareDatetime | None, Field(description='ISO 8601 flight end time for this package')
    ] = None
    paused: Annotated[
        bool | None, Field(description='Whether this package is currently paused by the buyer')
    ] = None
    canceled: Annotated[
        bool | None,
        Field(
            description='Whether this package has been canceled. Canceled packages stop delivery and cannot be reactivated.'
        ),
    ] = None
    cancellation: Annotated[
        Cancellation4 | None,
        Field(description='Cancellation metadata. Present only when canceled is true.'),
    ] = None
    creative_deadline: Annotated[
        AwareDatetime | None,
        Field(
            description="ISO 8601 timestamp for creative upload or change deadline for this package. After this deadline, creative changes are rejected. When absent, the media buy's creative_deadline applies."
        ),
    ] = None
    creative_approvals: Annotated[
        list[CreativeApproval] | None,
        Field(
            description='Approval status for each creative assigned to this package. Absent when no creatives have been assigned.'
        ),
    ] = None
    format_ids_pending: Annotated[
        list[FormatIdsPendingItem] | None,
        Field(
            description='Format IDs from the original create_media_buy format_ids_to_provide that have not yet been uploaded via sync_creatives. When empty or absent, all required formats have been provided.'
        ),
    ] = None
    snapshot_unavailable_reason: Annotated[
        SnapshotUnavailableReason | None,
        Field(
            description='Machine-readable reason the snapshot is omitted. Present only when include_snapshot was true and snapshot is unavailable for this package.'
        ),
    ] = None
    snapshot: Annotated[
        Snapshot | None,
        Field(
            description='Near-real-time delivery snapshot for this package. Only present when include_snapshot was true in the request. Represents the latest available entity-level stats from the platform — not billing-grade data.'
        ),
    ] = None
    ext: Annotated[
        dict[str, Any] | None,
        Field(
            description='Extension object for platform-specific, vendor-namespaced parameters. Extensions are always optional and must be namespaced under a vendor/platform key (e.g., ext.gam, ext.roku). Used for custom capabilities, partner-specific configuration, and features being proposed for standardization.',
            title='Extension Object',
        ),
    ] = None


class MediaBuy(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    media_buy_id: Annotated[str, Field(description="Seller's unique identifier for the media buy")]
    account: Annotated[
        Account | None,
        Field(
            description='Account billed for this media buy',
            examples=[
                {
                    'description': 'Direct advertiser account',
                    'data': {
                        'account_id': 'acc_acme_direct',
                        'name': 'Acme',
                        'advertiser': 'Acme Corp',
                        'brand': {'domain': 'acme-corp.com'},
                        'operator': 'acme-corp.com',
                        'status': 'active',
                        'billing': 'operator',
                        'account_scope': 'brand',
                        'rate_card': 'acme_vip_2024',
                        'payment_terms': 'net_30',
                    },
                },
                {
                    'description': 'Advertiser account with agency billing proxy',
                    'data': {
                        'account_id': 'acc_acme_pinnacle',
                        'name': 'Acme c/o Pinnacle',
                        'advertiser': 'Acme Corp',
                        'billing_proxy': 'Pinnacle Media',
                        'brand': {'domain': 'acme-corp.com'},
                        'operator': 'pinnacle-media.com',
                        'status': 'active',
                        'billing': 'operator',
                        'account_scope': 'operator_brand',
                        'rate_card': 'acme_vip_2024',
                        'payment_terms': 'net_60',
                    },
                },
                {
                    'description': 'Agency as direct buyer',
                    'data': {
                        'account_id': 'acc_pinnacle',
                        'name': 'Pinnacle',
                        'advertiser': 'Pinnacle Media',
                        'brand': {'domain': 'pinnacle-media.com'},
                        'operator': 'pinnacle-media.com',
                        'status': 'active',
                        'billing': 'operator',
                        'account_scope': 'operator',
                        'rate_card': 'agency_standard',
                        'payment_terms': 'net_45',
                    },
                },
                {
                    'description': 'Account with brand identity and operator (via sync_accounts)',
                    'data': {
                        'account_id': 'acc_spark_001',
                        'name': 'Spark (via Pinnacle)',
                        'advertiser': 'Nova Brands',
                        'status': 'active',
                        'brand': {'domain': 'nova-brands.com', 'brand_id': 'spark'},
                        'operator': 'pinnacle-media.com',
                        'billing': 'agent',
                        'account_scope': 'operator_brand',
                        'payment_terms': 'net_30',
                    },
                },
                {
                    'description': 'Pending account awaiting seller approval',
                    'data': {
                        'account_id': 'acc_glow_pending',
                        'name': 'Glow',
                        'advertiser': 'Nova Brands',
                        'status': 'pending_approval',
                        'brand': {'domain': 'nova-brands.com', 'brand_id': 'glow'},
                        'operator': 'pinnacle-media.com',
                        'billing': 'operator',
                        'account_scope': 'brand',
                    },
                },
                {
                    'description': 'Agency operates but advertiser is billed directly with structured billing entity',
                    'data': {
                        'account_id': 'acc_acme_direct_bill',
                        'name': 'Acme (billed direct)',
                        'advertiser': 'Acme Corp',
                        'brand': {'domain': 'acme-corp.com'},
                        'operator': 'pinnacle-media.com',
                        'status': 'active',
                        'billing': 'advertiser',
                        'billing_entity': {
                            'legal_name': 'Acme Corporation GmbH',
                            'vat_id': 'DE987654321',
                            'address': {
                                'street': 'Hauptstrasse 42',
                                'city': 'Munich',
                                'postal_code': '80331',
                                'country': 'DE',
                            },
                            'contacts': [
                                {
                                    'role': 'billing',
                                    'name': 'AP Department',
                                    'email': 'billing@acme-corp.com',
                                }
                            ],
                        },
                        'account_scope': 'operator_brand',
                        'payment_terms': 'net_30',
                    },
                },
            ],
            title='Account',
        ),
    ] = None
    invoice_recipient: Annotated[
        InvoiceRecipient | None,
        Field(
            description='Per-buy invoice recipient when provided at creation. Confirms the seller accepted the billing override. Bank details are omitted (write-only).',
            examples=[
                {
                    'description': 'German agency with full B2B details',
                    'data': {
                        'legal_name': 'Pinnacle Media GmbH',
                        'vat_id': 'DE123456789',
                        'registration_number': 'HRB 12345',
                        'address': {
                            'street': 'Friedrichstrasse 100',
                            'city': 'Berlin',
                            'postal_code': '10117',
                            'country': 'DE',
                        },
                        'contacts': [
                            {
                                'role': 'billing',
                                'name': 'Sam Adeyemi',
                                'email': 'billing@pinnacle-media.com',
                                'phone': '+49 30 12345678',
                            }
                        ],
                        'bank': {
                            'account_holder': 'Pinnacle Media GmbH',
                            'iban': 'DE89370400440532013000',
                            'bic': 'COBADEFFXXX',
                        },
                    },
                },
                {
                    'description': 'US advertiser with EIN and domestic bank details',
                    'data': {
                        'legal_name': 'Acme Corporation',
                        'tax_id': '12-3456789',
                        'address': {
                            'street': '123 Main St',
                            'city': 'New York',
                            'postal_code': '10001',
                            'region': 'NY',
                            'country': 'US',
                        },
                        'contacts': [
                            {
                                'role': 'billing',
                                'name': 'AP Department',
                                'email': 'ap@acme-corp.com',
                            }
                        ],
                        'bank': {
                            'account_holder': 'Acme Corporation',
                            'routing_number': '021000021',
                            'account_number': '123456789',
                        },
                    },
                },
            ],
            title='Business Entity',
        ),
    ] = None
    status: Annotated[
        Status11, Field(description='Status of a media buy.', title='Media Buy Status')
    ]
    currency: Annotated[
        str,
        Field(
            description='ISO 4217 currency code (e.g., USD, EUR, GBP) for monetary values at this media buy level. total_budget is always denominated in this currency. Package-level fields may override with package.currency.',
            pattern='^[A-Z]{3}$',
        ),
    ]
    total_budget: Annotated[
        float,
        Field(
            description='Total budget amount across all packages, denominated in media_buy.currency',
            ge=0.0,
        ),
    ]
    start_time: Annotated[
        AwareDatetime | None,
        Field(
            description='ISO 8601 flight start time for this media buy (earliest package start_time). Avoids requiring buyers to compute min(packages[].start_time).'
        ),
    ] = None
    end_time: Annotated[
        AwareDatetime | None,
        Field(
            description='ISO 8601 flight end time for this media buy (latest package end_time). Avoids requiring buyers to compute max(packages[].end_time).'
        ),
    ] = None
    creative_deadline: Annotated[
        AwareDatetime | None, Field(description='ISO 8601 timestamp for creative upload deadline')
    ] = None
    confirmed_at: Annotated[
        AwareDatetime | None,
        Field(
            description='ISO 8601 timestamp when the seller confirmed this media buy. A successful create_media_buy response constitutes order confirmation.'
        ),
    ] = None
    cancellation: Annotated[
        Cancellation | None,
        Field(description="Cancellation metadata. Present only when status is 'canceled'."),
    ] = None
    revision: Annotated[
        int | None,
        Field(
            description='Current revision number. Pass this in update_media_buy for optimistic concurrency.',
            ge=1,
        ),
    ] = None
    created_at: Annotated[AwareDatetime | None, Field(description='Creation timestamp')] = None
    updated_at: Annotated[AwareDatetime | None, Field(description='Last update timestamp')] = None
    valid_actions: Annotated[
        list[ValidAction] | None,
        Field(
            description='Actions the buyer can perform on this media buy in its current state. Eliminates the need for agents to internalize the state machine — the seller declares what is permitted right now.'
        ),
    ] = None
    history: Annotated[
        list[HistoryItem] | None,
        Field(
            description='Revision history entries, most recent first. Only present when include_history > 0 in the request. Each entry represents a state change or update to the media buy. Entries are append-only: sellers MUST NOT modify or delete previously emitted history entries. Callers MAY cache entries by revision number. Returns min(N, available entries) when include_history exceeds the total.'
        ),
    ] = None
    packages: Annotated[
        list[Package],
        Field(
            description='Packages within this media buy, augmented with creative approval status and optional delivery snapshots'
        ),
    ]
    ext: Annotated[
        dict[str, Any] | None,
        Field(
            description='Extension object for platform-specific, vendor-namespaced parameters. Extensions are always optional and must be namespaced under a vendor/platform key (e.g., ext.gam, ext.roku). Used for custom capabilities, partner-specific configuration, and features being proposed for standardization.',
            title='Extension Object',
        ),
    ] = None


class Recovery(Enum):
    transient = 'transient'
    correctable = 'correctable'
    terminal = 'terminal'


class Error(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    code: Annotated[
        str,
        Field(
            description='Error code for programmatic handling. Standard codes are defined in error-code.json and enable autonomous agent recovery. Sellers MAY use codes not in the standard vocabulary for platform-specific errors; agents MUST handle unknown codes gracefully by falling back to the recovery classification.',
            max_length=64,
            min_length=1,
        ),
    ]
    message: Annotated[str, Field(description='Human-readable error message')]
    field: Annotated[
        str | None,
        Field(description="Field path associated with the error (e.g., 'packages[0].targeting')"),
    ] = None
    suggestion: Annotated[str | None, Field(description='Suggested fix for the error')] = None
    retry_after: Annotated[
        float | None,
        Field(
            description='Seconds to wait before retrying the operation. Sellers MUST return values between 1 and 3600. Clients MUST clamp values outside this range.',
            ge=1.0,
            le=3600.0,
        ),
    ] = None
    details: Annotated[
        dict[str, Any] | None, Field(description='Additional task-specific error details')
    ] = None
    recovery: Annotated[
        Recovery | None,
        Field(
            description='Agent recovery classification. transient: retry after delay (rate limit, service unavailable, timeout). correctable: fix the request and resend (invalid field, budget too low, creative rejected). terminal: requires human action (account suspended, payment required, account not found).'
        ),
    ] = None


class Pagination(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    has_more: Annotated[
        bool, Field(description='Whether more results are available beyond this page')
    ]
    cursor: Annotated[
        str | None,
        Field(
            description='Opaque cursor to pass in the next request to fetch the next page. Only present when has_more is true.'
        ),
    ] = None
    total_count: Annotated[
        int | None,
        Field(
            description='Total number of items matching the query across all pages. Optional because not all backends can efficiently compute this.',
            ge=0,
        ),
    ] = None


class GetMediaBuysResponse(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    media_buys: Annotated[
        list[MediaBuy],
        Field(
            description='Array of media buys with status, creative approval state, and optional delivery snapshots'
        ),
    ]
    errors: Annotated[
        list[Error] | None, Field(description='Task-specific errors (e.g., media buy not found)')
    ] = None
    pagination: Annotated[
        Pagination | None,
        Field(
            description='Pagination metadata for the media_buys array.', title='Pagination Response'
        ),
    ] = None
    sandbox: Annotated[
        bool | None,
        Field(description='When true, this response contains simulated data from sandbox mode.'),
    ] = None
    context: Annotated[
        dict[str, Any] | None,
        Field(
            description="Opaque correlation data that is echoed unchanged in responses. Used for internal tracking, UI session IDs, trace IDs, and other caller-specific identifiers that don't affect protocol behavior. Context data is never parsed by AdCP agents - it's simply preserved and returned.",
            title='Context Object',
        ),
    ] = None
    ext: Annotated[
        dict[str, Any] | None,
        Field(
            description='Extension object for platform-specific, vendor-namespaced parameters. Extensions are always optional and must be namespaced under a vendor/platform key (e.g., ext.gam, ext.roku). Used for custom capabilities, partner-specific configuration, and features being proposed for standardization.',
            title='Extension Object',
        ),
    ] = None
