# generated by datamodel-codegen:
#   filename:  property/create_property_list_response.json
#   timestamp: 2026-04-22T04:27:52+00:00

from __future__ import annotations

from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import ConfigDict, Field

from ..core import context as context_1
from ..core import ext as ext_1
from . import property_list


class CreatePropertyListResponse(AdCPBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    list: Annotated[property_list.PropertyList, Field(description="The created property list")]
    auth_token: Annotated[
        str,
        Field(
            description="Token that can be shared with sellers to authorize fetching this list. Store this - it is only returned at creation time."
        ),
    ]
    context: context_1.ContextObject | None = None
    ext: ext_1.ExtensionObject | None = None
