# generated by datamodel-codegen:
#   filename:  property/delete_property_list_response.json
#   timestamp: 2026-04-22T04:27:52+00:00

from __future__ import annotations

from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import ConfigDict, Field

from ..core import context as context_1
from ..core import ext as ext_1


class DeletePropertyListResponse(AdCPBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    deleted: Annotated[bool, Field(description="Whether the list was successfully deleted")]
    list_id: Annotated[str, Field(description="ID of the deleted list")]
    context: context_1.ContextObject | None = None
    ext: ext_1.ExtensionObject | None = None
