# generated by datamodel-codegen:
#   filename:  property/list_property_lists_request.json
#   timestamp: 2026-03-16T00:33:16+00:00

from __future__ import annotations

from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import ConfigDict, Field

from ..core import context as context_1
from ..core import ext as ext_1
from ..core import pagination_request


class ListPropertyListsRequest(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    principal: Annotated[
        str | None, Field(description='Filter to lists owned by this principal')
    ] = None
    name_contains: Annotated[
        str | None, Field(description='Filter to lists whose name contains this string')
    ] = None
    pagination: pagination_request.PaginationRequest | None = None
    context: context_1.ContextObject | None = None
    ext: ext_1.ExtensionObject | None = None
