# generated by datamodel-codegen:
#   filename:  property/update_property_list_response.json
#   timestamp: 2026-03-16T00:33:16+00:00

from __future__ import annotations

from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import ConfigDict, Field

from ..core import ext as ext_1
from . import property_list


class UpdatePropertyListResponse(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    list: Annotated[property_list.PropertyList, Field(description='The updated property list')]
    ext: ext_1.ExtensionObject | None = None
