# generated by datamodel-codegen:
#   filename:  property/validate_property_delivery_request.json
#   timestamp: 2026-03-16T00:33:16+00:00

from __future__ import annotations

from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import ConfigDict, Field

from ..core import ext as ext_1
from . import delivery_record


class ValidatePropertyDeliveryRequest(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    list_id: Annotated[str, Field(description='ID of the property list to validate against')]
    records: Annotated[
        list[delivery_record.DeliveryRecord],
        Field(
            description='Delivery records to validate. Each record represents impressions delivered to a property identifier.',
            max_length=10000,
            min_length=1,
        ),
    ]
    include_compliant: Annotated[
        bool | None,
        Field(
            description='Include compliant records in results (default: only return non_compliant, unmodeled, and unidentified)'
        ),
    ] = False
    ext: ext_1.ExtensionObject | None = None
