# generated by datamodel-codegen:
#   filename:  compliance/comply_test_controller_response.json
#   timestamp: 2026-04-21T22:41:55+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Literal

from adcp.types.base import AdCPBaseModel
from pydantic import ConfigDict, Field

from ..core import context as context_1
from ..core import ext as ext_1


class Scenario(Enum):
    force_creative_status = "force_creative_status"
    force_account_status = "force_account_status"
    force_media_buy_status = "force_media_buy_status"
    force_session_status = "force_session_status"
    simulate_delivery = "simulate_delivery"
    simulate_budget_spend = "simulate_budget_spend"
    seed_product = "seed_product"
    seed_pricing_option = "seed_pricing_option"
    seed_creative = "seed_creative"
    seed_plan = "seed_plan"
    seed_media_buy = "seed_media_buy"


class Error(Enum):
    INVALID_TRANSITION = "INVALID_TRANSITION"
    INVALID_STATE = "INVALID_STATE"
    NOT_FOUND = "NOT_FOUND"
    UNKNOWN_SCENARIO = "UNKNOWN_SCENARIO"
    INVALID_PARAMS = "INVALID_PARAMS"
    FORBIDDEN = "FORBIDDEN"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class ComplyTestControllerResponse1(AdCPBaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    success: Literal[True]
    scenarios: Annotated[
        list[Scenario],
        Field(
            description="Scenarios this seller has implemented. Runners and sellers MUST accept unknown scenario strings (open-for-extension) — new scenarios may be added in additive minor bumps."
        ),
    ]
    context: context_1.ContextObject | None = None
    ext: ext_1.ExtensionObject | None = None


class ComplyTestControllerResponse2(AdCPBaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    success: Literal[True]
    previous_state: Annotated[str, Field(description="State before this transition")]
    current_state: Annotated[str, Field(description="State after this transition")]
    message: Annotated[
        str | None, Field(description="Human-readable description of the transition")
    ] = None
    context: context_1.ContextObject | None = None
    ext: ext_1.ExtensionObject | None = None


class ComplyTestControllerResponse3(AdCPBaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    success: Literal[True]
    simulated: Annotated[
        dict[str, Any],
        Field(description="Values injected or applied by this call. Shape depends on scenario."),
    ]
    cumulative: Annotated[
        dict[str, Any] | None,
        Field(description="Running totals across all simulation calls (simulate_delivery only)"),
    ] = None
    message: str | None = None
    context: context_1.ContextObject | None = None
    ext: ext_1.ExtensionObject | None = None


class ComplyTestControllerResponse4(AdCPBaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    success: Literal[False]
    error: Annotated[Error, Field(description="Structured error code")]
    error_detail: Annotated[
        str | None, Field(description="Human-readable explanation of the failure")
    ] = None
    current_state: Annotated[
        str | None, Field(description="Current state of the entity, or null if not found")
    ] = None
    context: context_1.ContextObject | None = None
    ext: ext_1.ExtensionObject | None = None


ComplyTestControllerResponse = (
    ComplyTestControllerResponse1
    | ComplyTestControllerResponse2
    | ComplyTestControllerResponse3
    | ComplyTestControllerResponse4
)
