# generated by datamodel-codegen:
#   filename:  compliance/comply_test_controller_request.json
#   timestamp: 2026-04-22T04:27:52+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from adcp.types.base import AdCPBaseModel
from pydantic import ConfigDict, Field

from ..core import context as context_1
from ..core import ext as ext_1


class Scenario(Enum):
    list_scenarios = "list_scenarios"
    force_creative_status = "force_creative_status"
    force_account_status = "force_account_status"
    force_media_buy_status = "force_media_buy_status"
    force_session_status = "force_session_status"
    simulate_delivery = "simulate_delivery"
    simulate_budget_spend = "simulate_budget_spend"
    seed_product = "seed_product"
    seed_pricing_option = "seed_pricing_option"
    seed_creative = "seed_creative"
    seed_plan = "seed_plan"
    seed_media_buy = "seed_media_buy"


class ReportedSpend(AdCPBaseModel):
    amount: Annotated[float, Field(ge=0.0)]
    currency: Annotated[str, Field(pattern="^[A-Z]{3}$")]


class Params(AdCPBaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    creative_id: Annotated[
        str | None,
        Field(
            description="Creative to transition (force_creative_status) or seed (seed_creative)."
        ),
    ] = None
    account_id: Annotated[
        str | None,
        Field(
            description="Account to transition. Used by force_account_status and simulate_budget_spend."
        ),
    ] = None
    media_buy_id: Annotated[
        str | None,
        Field(
            description="Media buy to transition (force_media_buy_status, simulate_delivery, simulate_budget_spend) or seed (seed_media_buy)."
        ),
    ] = None
    session_id: Annotated[
        str | None, Field(description="Session to transition. Used by force_session_status.")
    ] = None
    product_id: Annotated[
        str | None,
        Field(description="Product to seed. Used by seed_product and seed_pricing_option."),
    ] = None
    pricing_option_id: Annotated[
        str | None,
        Field(
            description="Pricing option to seed, scoped to a product. Used by seed_pricing_option."
        ),
    ] = None
    plan_id: Annotated[str | None, Field(description="Plan to seed. Used by seed_plan.")] = None
    fixture: Annotated[
        dict[str, Any] | None,
        Field(
            description="Arbitrary fixture payload carried by seed_* scenarios. Shape matches the domain object the seed scenario creates (product, creative, plan, media buy, pricing option). Seller MAY reject malformed fixtures with INVALID_PARAMS. Kept permissive so storyboard authors can declare the minimum shape each test needs without the spec locking down every field."
        ),
    ] = None
    status: Annotated[
        str | None,
        Field(
            description="Target status for the resource. Type depends on scenario: creative-status for force_creative_status, account-status for force_account_status, media-buy-status for force_media_buy_status. For force_session_status, must be 'complete' or 'terminated'."
        ),
    ] = None
    rejection_reason: Annotated[
        str | None,
        Field(
            description="Reason for rejection. Used by force_creative_status and force_media_buy_status when status = rejected."
        ),
    ] = None
    termination_reason: Annotated[
        str | None,
        Field(
            description="Reason for termination (e.g., session_timeout, host_terminated, policy_violation). Used by force_session_status when status = terminated."
        ),
    ] = None
    impressions: Annotated[
        int | None, Field(description="Impressions to simulate. Used by simulate_delivery.", ge=0)
    ] = None
    clicks: Annotated[
        int | None, Field(description="Clicks to simulate. Used by simulate_delivery.", ge=0)
    ] = None
    conversions: Annotated[
        int | None, Field(description="Conversions to simulate. Used by simulate_delivery.", ge=0)
    ] = None
    reported_spend: Annotated[
        ReportedSpend | None,
        Field(
            description="Spend as reported in delivery data. Does not affect budget. Used by simulate_delivery."
        ),
    ] = None
    spend_percentage: Annotated[
        float | None,
        Field(
            description="Spend to this percentage of budget (0–100). Used by simulate_budget_spend.",
            ge=0.0,
            le=100.0,
        ),
    ] = None


class ComplyTestControllerRequest(AdCPBaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    scenario: Annotated[
        Scenario,
        Field(
            description="Test scenario to execute. 'list_scenarios' discovers supported scenarios. 'force_*' and 'simulate_*' trigger state transitions. 'seed_*' scenarios pre-populate fixtures (product, pricing option, creative, plan, media buy) so storyboards can reference them by stable ID without the implementer having to guess which IDs the conformance suite expects."
        ),
    ]
    params: Annotated[
        Params | None,
        Field(
            description="Scenario-specific parameters. Required for all scenarios except list_scenarios."
        ),
    ] = None
    context: context_1.ContextObject | None = None
    ext: ext_1.ExtensionObject | None = None
