# generated by datamodel-codegen:
#   filename:  protocol/get_principal_request.json
#   timestamp: 2026-10-04T02:05:29+00:00

from __future__ import annotations

from adcp.types.base import AdcpRequest

from pydantic import ConfigDict

from ..core import context as context_1
from ..core import ext as ext_1
from ..core.version_envelope import AdcpVersionEnvelope


class GetPrincipalRequest(AdcpRequest, AdcpVersionEnvelope):
    model_config = ConfigDict(
        extra='allow',
    )
    context: context_1.ContextObject | None = None
    ext: ext_1.ExtensionObject | None = None
