# generated by datamodel-codegen:
#   filename:  creative/validate_input_response.json
#   timestamp: 2026-10-04T02:05:29+00:00

from __future__ import annotations

from adcp.types.base import AdcpResponse

from typing import Annotated

from pydantic import ConfigDict, Field

from ..core.protocol_envelope import ProtocolEnvelope
from ..core.version_envelope import AdcpVersionEnvelope
from . import validate_input_result


class ValidateInputResponse(AdcpResponse, AdcpVersionEnvelope, ProtocolEnvelope):
    model_config = ConfigDict(
        extra='allow',
    )
    results: Annotated[
        list[validate_input_result.ValidateInputResult],
        Field(description='Per-target validation results.'),
    ]
