# generated by datamodel-codegen:
#   filename:  governance/get_plan_audit_logs_response.json
#   timestamp: 2026-03-16T00:33:16+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import AnyUrl, AwareDatetime, ConfigDict, Field

from ..enums import escalation_severity, outcome_type


class Status(Enum):
    active = 'active'
    suspended = 'suspended'
    completed = 'completed'


class Budget(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    authorized: Annotated[
        float | None, Field(description='Total authorized budget from the plan.')
    ] = None
    committed: Annotated[
        float | None, Field(description='Total budget committed from confirmed outcomes.')
    ] = None
    remaining: Annotated[float | None, Field(description='Authorized minus committed.')] = None
    utilization_pct: Annotated[
        float | None, Field(description='Committed as a percentage of authorized.')
    ] = None


class ChannelAllocation(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    committed: Annotated[float | None, Field(description='Budget committed to this channel.')] = (
        None
    )
    pct: Annotated[
        float | None, Field(description="Channel's share of the authorized total budget.")
    ] = None


class Campaign(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    buyer_campaign_ref: Annotated[str, Field(description='Campaign identifier.')]
    status: Annotated[Status, Field(description='Campaign status.')]
    committed: Annotated[float, Field(description='Budget committed in this campaign.')]
    active_media_buys: Annotated[
        list[str] | None, Field(description='Media buy IDs currently active.')
    ] = None


class Statuses(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    approved: int | None = None
    denied: int | None = None
    conditions: int | None = None
    escalated: int | None = None


class Escalation(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    check_id: Annotated[str, Field(description='The escalated governance check.')]
    reason: Annotated[str, Field(description='Why it was escalated.')]
    resolution: Annotated[
        str | None,
        Field(description="How it was resolved (e.g., 'approved_by_human', 'rejected_by_human')."),
    ] = None
    resolved_at: Annotated[
        AwareDatetime | None, Field(description='ISO 8601 resolution timestamp.')
    ] = None


class EscalationRateTrend(Enum):
    increasing = 'increasing'
    stable = 'stable'
    declining = 'declining'


class Thresholds(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    escalation_rate_max: Annotated[
        float | None,
        Field(
            description='Maximum acceptable escalation rate. A rate above this suggests policy miscalibration.',
            ge=0.0,
            le=1.0,
        ),
    ] = None
    escalation_rate_min: Annotated[
        float | None,
        Field(
            description='Minimum acceptable escalation rate. A rate below this may indicate eroding oversight.',
            ge=0.0,
            le=1.0,
        ),
    ] = None
    auto_approval_rate_max: Annotated[
        float | None, Field(description='Maximum acceptable auto-approval rate.', ge=0.0, le=1.0)
    ] = None
    human_override_rate_max: Annotated[
        float | None,
        Field(
            description="Maximum acceptable human override rate. A high rate suggests the governance agent's recommendations are poorly calibrated.",
            ge=0.0,
            le=1.0,
        ),
    ] = None


class DriftMetrics(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    escalation_rate: Annotated[
        float | None,
        Field(description='Fraction of checks that resulted in escalation.', ge=0.0, le=1.0),
    ] = None
    escalation_rate_trend: Annotated[
        EscalationRateTrend | None,
        Field(description="Direction of escalation rate over the plan's lifetime."),
    ] = None
    auto_approval_rate: Annotated[
        float | None,
        Field(
            description='Fraction of checks approved without human intervention.', ge=0.0, le=1.0
        ),
    ] = None
    human_override_rate: Annotated[
        float | None,
        Field(
            description="Fraction of escalations where the human overrode the governance agent's recommendation.",
            ge=0.0,
            le=1.0,
        ),
    ] = None
    mean_confidence: Annotated[
        float | None,
        Field(
            description='Average confidence score across all findings. Present when findings include confidence scores.',
            ge=0.0,
            le=1.0,
        ),
    ] = None
    thresholds: Annotated[
        Thresholds | None,
        Field(
            description='Organization-defined thresholds for drift metrics. When a metric crosses its threshold, the governance agent SHOULD include a finding on the next check. Set by the organization in governance agent configuration, echoed here for visibility.'
        ),
    ] = None


class Summary(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    checks_performed: Annotated[
        int | None, Field(description='Total governance checks performed.')
    ] = None
    outcomes_reported: Annotated[int | None, Field(description='Total outcomes reported.')] = None
    statuses: Annotated[
        Statuses | None, Field(description='Count of each governance check status.')
    ] = None
    findings_count: Annotated[
        int | None, Field(description='Total findings across all checks and outcomes.')
    ] = None
    escalations: Annotated[
        list[Escalation] | None, Field(description='All escalations and their resolutions.')
    ] = None
    drift_metrics: Annotated[
        DriftMetrics | None,
        Field(
            description='Aggregate governance metrics for detecting oversight drift. A declining escalation rate may indicate well-calibrated governance or eroding human oversight -- surfacing the trend lets the organization make that judgment.'
        ),
    ] = None


class Type(Enum):
    check = 'check'
    outcome = 'outcome'


class Status8(Enum):
    approved = 'approved'
    denied = 'denied'
    conditions = 'conditions'
    escalated = 'escalated'


class Binding(Enum):
    proposed = 'proposed'
    committed = 'committed'


class Finding(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    category_id: str
    policy_id: str | None = None
    severity: escalation_severity.EscalationSeverity
    explanation: str
    confidence: Annotated[float | None, Field(ge=0.0, le=1.0)] = None


class Entry(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: Annotated[str, Field(description='Entry identifier.')]
    type: Annotated[Type, Field(description='Entry type.')]
    timestamp: Annotated[AwareDatetime, Field(description='ISO 8601 timestamp.')]
    plan_id: Annotated[
        str | None,
        Field(
            description='Plan this entry belongs to. Present when querying multiple plans or a portfolio.'
        ),
    ] = None
    caller: Annotated[
        AnyUrl | None,
        Field(
            description='URL of the agent that made the request. Resolved from the credentials used on the governance callback.'
        ),
    ] = None
    tool: Annotated[str | None, Field(description='The AdCP tool (present for check entries).')] = (
        None
    )
    status: Annotated[
        Status8 | None, Field(description='Governance check status (present for check entries).')
    ] = None
    binding: Annotated[
        Binding | None,
        Field(
            description='Whether the check was proposed or committed (present for check entries).'
        ),
    ] = None
    explanation: Annotated[
        str | None,
        Field(
            description='Human-readable explanation of the governance decision (present for check entries).'
        ),
    ] = None
    policies_evaluated: Annotated[
        list[str] | None,
        Field(
            description='Registry policy IDs evaluated during this check (present for check entries).'
        ),
    ] = None
    categories_evaluated: Annotated[
        list[str] | None,
        Field(
            description="Governance categories evaluated (e.g., 'budget_authority', 'regulatory_compliance'). Present for check entries."
        ),
    ] = None
    findings: Annotated[
        list[Finding] | None,
        Field(
            description='Findings from this check or outcome. Same structure as check_governance response findings.'
        ),
    ] = None
    outcome: Annotated[
        outcome_type.OutcomeType | None,
        Field(description='Outcome type (present for outcome entries).'),
    ] = None
    committed_budget: Annotated[
        float | None, Field(description='Budget committed (present for completed outcome entries).')
    ] = None
    media_buy_id: Annotated[
        str | None, Field(description='Media buy ID (present for delivery outcome entries).')
    ] = None
    outcome_status: Annotated[
        str | None, Field(description='Outcome status (present for outcome entries).')
    ] = None


class Plan(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    plan_id: Annotated[str, Field(description='Plan identifier.')]
    plan_version: Annotated[int, Field(description='Current plan version.')]
    status: Annotated[Status, Field(description='Plan lifecycle status.')]
    budget: Annotated[Budget, Field(description='Budget state.')]
    channel_allocation: Annotated[
        dict[str, ChannelAllocation] | None,
        Field(description='Current channel mix. Keyed by channel ID.'),
    ] = None
    campaigns: Annotated[list[Campaign], Field(description='Per-campaign breakdown.')]
    summary: Annotated[Summary, Field(description='Aggregate validation and outcome statistics.')]
    entries: Annotated[
        list[Entry] | None,
        Field(description='Ordered audit trail. Only present when include_entries is true.'),
    ] = None


class GetPlanAuditLogsResponse(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    plans: Annotated[list[Plan], Field(description='Audit data for each requested plan.')]
