# generated by datamodel-codegen:
#   filename:  governance/governance_context.json
#   timestamp: 2026-03-16T00:33:16+00:00

from __future__ import annotations

from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import AnyUrl, AwareDatetime, ConfigDict, Field


class TotalBudget(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    amount: Annotated[float, Field(description='Budget amount.')]
    currency: Annotated[str, Field(description='ISO 4217 currency code.')]


class Flight(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    start: Annotated[AwareDatetime, Field(description='Flight start (ISO 8601).')]
    end: Annotated[AwareDatetime, Field(description='Flight end (ISO 8601).')]


class GovernanceContext(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    total_budget: Annotated[
        TotalBudget | None, Field(description='Total budget for the action.')
    ] = None
    countries: Annotated[
        list[str] | None,
        Field(description='ISO 3166-1 alpha-2 country codes targeted by this action.'),
    ] = None
    channels: Annotated[
        list[str] | None, Field(description='Channels targeted by this action.')
    ] = None
    flight: Annotated[Flight | None, Field(description='Flight dates for this action.')] = None
    seller_url: Annotated[
        AnyUrl | None, Field(description='URL of the seller agent this action targets.')
    ] = None
