# generated by datamodel-codegen:
#   filename:  governance/report_plan_outcome_request.json
#   timestamp: 2026-03-16T00:33:16+00:00

from __future__ import annotations

from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import AwareDatetime, ConfigDict, Field

from ..core import planned_delivery as planned_delivery_1
from ..enums import outcome_type


class Package(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    budget: Annotated[float | None, Field(ge=0.0)] = None


class ReportingPeriod(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    start: AwareDatetime
    end: AwareDatetime


class Delivery(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    media_buy_id: Annotated[str | None, Field(description='The media buy being reported on.')] = (
        None
    )
    reporting_period: Annotated[
        ReportingPeriod | None,
        Field(description='Start and end timestamps for the reporting window.'),
    ] = None
    impressions: Annotated[
        int | None, Field(description='Impressions delivered in the period.', ge=0)
    ] = None
    spend: Annotated[float | None, Field(description='Spend in the period.')] = None
    cpm: Annotated[float | None, Field(description='Effective CPM for the period.')] = None
    viewability_rate: Annotated[float | None, Field(description='Viewability rate (0-1).')] = None
    completion_rate: Annotated[float | None, Field(description='Video completion rate (0-1).')] = (
        None
    )


class Error(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Annotated[str | None, Field(description='Error code from the seller.')] = None
    message: Annotated[str | None, Field(description='Human-readable error description.')] = None


class SellerResponse(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    media_buy_id: Annotated[str | None, Field(description="Seller's media buy identifier.")] = None
    buyer_ref: Annotated[
        str | None, Field(description='The buyer reference echoed back by the seller.')
    ] = None
    committed_budget: Annotated[
        float | None,
        Field(
            description='Total budget committed across all confirmed packages. When present, the governance agent uses this directly instead of summing package budgets.',
            ge=0.0,
        ),
    ] = None
    packages: Annotated[
        list[Package] | None,
        Field(description='Confirmed packages with actual budget and targeting.'),
    ] = None
    planned_delivery: Annotated[
        planned_delivery_1.PlannedDelivery | None,
        Field(
            description="What the seller said it will deliver. When seller-side governance is not configured, this is the governance agent's only view of the seller's delivery parameters."
        ),
    ] = None
    creative_deadline: Annotated[
        AwareDatetime | None, Field(description='ISO 8601 deadline for creative submission.')
    ] = None


class ReportPlanOutcomeRequest(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    plan_id: Annotated[str, Field(description='The plan this outcome is for.')]
    check_id: Annotated[
        str | None,
        Field(
            description="The check_id from check_governance. Links the outcome to the governance check that authorized it. Required for 'completed' and 'failed' outcomes."
        ),
    ] = None
    buyer_campaign_ref: Annotated[str, Field(description='Campaign identifier.')]
    outcome: Annotated[outcome_type.OutcomeType, Field(description='Outcome type.')]
    seller_response: Annotated[
        SellerResponse | None,
        Field(description="The seller's full response. Required when outcome is 'completed'."),
    ] = None
    delivery: Annotated[
        Delivery | None, Field(description="Delivery metrics. Required when outcome is 'delivery'.")
    ] = None
    error: Annotated[
        Error | None, Field(description="Error details. Required when outcome is 'failed'.")
    ] = None
