# generated by datamodel-codegen:
#   filename:  content_standards/calibrate_content_request.json
#   timestamp: 2026-03-16T00:33:16+00:00

from __future__ import annotations

from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import Field

from . import artifact as artifact_1


class CalibrateContentRequest(AdCPBaseModel):
    standards_id: Annotated[str, Field(description='Standards configuration to calibrate against')]
    artifact: Annotated[artifact_1.Artifact, Field(description='Artifact to evaluate')]
