# generated by datamodel-codegen:
#   filename:  content_standards/get_content_standards_request.json
#   timestamp: 2026-03-16T00:33:16+00:00

from __future__ import annotations

from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import Field

from ..core import context as context_1
from ..core import ext as ext_1


class GetContentStandardsRequest(AdCPBaseModel):
    standards_id: Annotated[
        str, Field(description='Identifier for the standards configuration to retrieve')
    ]
    context: context_1.ContextObject | None = None
    ext: ext_1.ExtensionObject | None = None
