# generated by datamodel-codegen:
#   filename:  content_standards/validate_content_delivery_response.json
#   timestamp: 2026-03-16T00:33:16+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from adcp.types.base import AdCPBaseModel
from pydantic import Field

from ..core import context as context_1
from ..core import error
from ..core import ext as ext_1


class Summary(AdCPBaseModel):
    total_records: int
    passed_records: int
    failed_records: int


class Verdict(Enum):
    pass_ = 'pass'
    fail = 'fail'


class Status(Enum):
    passed = 'passed'
    failed = 'failed'
    warning = 'warning'
    unevaluated = 'unevaluated'


class Feature(AdCPBaseModel):
    feature_id: str
    status: Status
    value: Any | None = None
    message: str | None = None
    rule_id: Annotated[
        str | None,
        Field(
            description='Which rule triggered this result (e.g., GARM category, Scope3 standard)'
        ),
    ] = None


class Result(AdCPBaseModel):
    record_id: Annotated[str, Field(description='Which delivery record was evaluated')]
    verdict: Annotated[Verdict, Field(description='Overall pass/fail verdict for this record')]
    features: Annotated[
        list[Feature] | None, Field(description='Optional feature-level breakdown')
    ] = None


class ValidateContentDeliveryResponse1(AdCPBaseModel):
    summary: Annotated[Summary, Field(description='Summary counts across all records')]
    results: Annotated[list[Result], Field(description='Per-record evaluation results')]
    context: context_1.ContextObject | None = None
    ext: ext_1.ExtensionObject | None = None


class ValidateContentDeliveryResponse2(AdCPBaseModel):
    errors: list[error.Error]
    context: context_1.ContextObject | None = None
    ext: ext_1.ExtensionObject | None = None


ValidateContentDeliveryResponse = ValidateContentDeliveryResponse1 | ValidateContentDeliveryResponse2
