# generated by datamodel-codegen:
#   filename:  content_standards/list_content_standards_response.json
#   timestamp: 2026-10-04T02:05:29+00:00

from __future__ import annotations

from adcp.types.base import AdcpResponse

from adcp.types.response_dispatch import ResponseArmDispatchMixin

from typing import Annotated

from pydantic import Field

from ..core import context as context_1
from ..core import error
from ..core import ext as ext_1
from ..core import pagination_response
from ..core.protocol_envelope import ProtocolEnvelope
from ..core.version_envelope import AdcpVersionEnvelope
from . import content_standards


class ListContentStandardsResponse(AdcpResponse, ResponseArmDispatchMixin, AdcpVersionEnvelope, ProtocolEnvelope):
    """Constructible compatibility base for generated response arms."""

    @classmethod
    def _response_arm_models(cls) -> tuple[type[ListContentStandardsResponse], ...]:
        return (
            ListContentStandardsResponse1,
            ListContentStandardsResponse2,
        )


class ListContentStandardsResponse2(ListContentStandardsResponse):
    errors: list[error.Error]
    context: context_1.ContextObject | None = None
    ext: ext_1.ExtensionObject | None = None


class ListContentStandardsResponse1(ListContentStandardsResponse):
    standards: Annotated[
        list[content_standards.ContentStandards],
        Field(description='Array of content standards configurations matching the filter criteria'),
    ]
    pagination: pagination_response.PaginationResponse | None = None
    context: context_1.ContextObject | None = None
    ext: ext_1.ExtensionObject | None = None
