# generated by datamodel-codegen:
#   filename:  core/budget_range.json
#   timestamp: 2026-10-04T01:14:11+00:00

from __future__ import annotations

from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import ConfigDict, Field, StrictFloat, model_validator


class BudgetRange(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    min: Annotated[StrictFloat | None, Field(ge=0.0)] = None
    max: Annotated[StrictFloat | None, Field(ge=0.0)] = None
    currency: Annotated[str, Field(pattern='^[A-Z]{3}$')]

    @model_validator(mode='after')
    def _require_schema_required_group(self) -> BudgetRange:
        # ``required`` asks whether the caller supplied the field, which is what
        # model_fields_set answers. An explicit null is a supplied value — on a
        # mutation input it is the command to clear — and a default the caller
        # never sent is not.
        for group in (('min',), ('max',),):
            if all(name in self.model_fields_set for name in group):
                return self
        raise ValueError(
            'BudgetRange requires at least one of these field groups: min | max'
        )
