# generated by datamodel-codegen:
#   filename:  core/context.json
#   timestamp: 2026-04-22T10:13:46+00:00

from __future__ import annotations

from adcp.types.base import AdCPBaseModel
from pydantic import ConfigDict


class ContextObject(AdCPBaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
