# generated by datamodel-codegen:
#   filename:  core/episode.json
#   timestamp: 2026-03-16T00:33:16+00:00

from __future__ import annotations

from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import AwareDatetime, ConfigDict, Field

from ..enums import derivative_type, episode_status
from . import ad_inventory_config
from . import content_rating as content_rating_1
from . import ext as ext_1
from . import talent


class DerivativeOf(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    episode_id: Annotated[str, Field(description='The source episode this content is derived from')]
    type: Annotated[
        derivative_type.DerivativeType, Field(description='What kind of derivative content this is')
    ]


class Episode(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    episode_id: Annotated[
        str, Field(description='Unique identifier for this episode within the show')
    ]
    show_id: Annotated[
        str | None,
        Field(
            description='Parent show reference. Required when the product spans multiple shows (has multiple entries in show_ids on the product).'
        ),
    ] = None
    name: Annotated[str | None, Field(description='Episode title')] = None
    season: Annotated[
        str | None, Field(description="Season identifier (e.g., '1', '2024', 'spring_2026')")
    ] = None
    episode_number: Annotated[
        str | None, Field(description="Episode number within the season (e.g., '3', '47')")
    ] = None
    scheduled_at: Annotated[
        AwareDatetime | None, Field(description='When the episode airs or publishes (ISO 8601)')
    ] = None
    status: Annotated[
        episode_status.EpisodeStatus | None, Field(description='Lifecycle status of the episode')
    ] = None
    duration_seconds: Annotated[
        int | None, Field(description='Expected duration of the episode in seconds', ge=0)
    ] = None
    flexible_end: Annotated[
        bool | None, Field(description='Whether the end time is approximate (live events, sports)')
    ] = None
    valid_until: Annotated[
        AwareDatetime | None,
        Field(
            description='When this episode data expires and should be re-queried. Agents should re-query before committing budget to products with tentative episodes.'
        ),
    ] = None
    content_rating: Annotated[
        content_rating_1.ContentRating | None,
        Field(
            description="Episode-specific content rating. Overrides the show's baseline content_rating when present."
        ),
    ] = None
    topics: Annotated[
        list[str] | None,
        Field(
            description="Content topics for this episode. Uses the same taxonomy as the show's genre_taxonomy when present. Enables episode-level brand safety evaluation beyond content_rating."
        ),
    ] = None
    guest_talent: Annotated[
        list[talent.Talent] | None,
        Field(
            description="Episode-specific guests and talent. Additive to the show's recurring talent."
        ),
    ] = None
    ad_inventory: Annotated[
        ad_inventory_config.AdInventoryConfiguration | None,
        Field(
            description='Break-based ad inventory for this episode. For non-break formats (host reads, integrations), use product placements.'
        ),
    ] = None
    derivative_of: Annotated[
        DerivativeOf | None,
        Field(
            description='When this episode is a clip, highlight, or recap derived from a full episode. The source episode_id must reference an episode within the same response.'
        ),
    ] = None
    ext: ext_1.ExtensionObject | None = None
