# generated by datamodel-codegen:
#   filename:  core/ext.json
#   timestamp: 2026-04-18T19:31:26+00:00

from __future__ import annotations

from adcp.types.base import AdCPBaseModel
from pydantic import ConfigDict


class ExtensionObject(AdCPBaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
