# generated by datamodel-codegen:
#   filename:  core/proposal.json
#   timestamp: 2026-03-16T00:33:16+00:00

from __future__ import annotations

from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import AwareDatetime, ConfigDict, Field

from . import delivery_forecast
from . import ext as ext_1
from . import product_allocation


class TotalBudgetGuidance(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    min: Annotated[float | None, Field(description='Minimum recommended budget', ge=0.0)] = None
    recommended: Annotated[
        float | None, Field(description='Recommended budget for optimal performance', ge=0.0)
    ] = None
    max: Annotated[
        float | None, Field(description='Maximum budget before diminishing returns', ge=0.0)
    ] = None
    currency: Annotated[str | None, Field(description='ISO 4217 currency code')] = None


class Proposal(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    proposal_id: Annotated[
        str,
        Field(
            description='Unique identifier for this proposal. Used to execute it via create_media_buy.'
        ),
    ]
    name: Annotated[str, Field(description='Human-readable name for this media plan proposal')]
    description: Annotated[
        str | None, Field(description='Explanation of the proposal strategy and what it achieves')
    ] = None
    allocations: Annotated[
        list[product_allocation.ProductAllocation],
        Field(
            description='Budget allocations across products. Allocation percentages MUST sum to 100. Publishers are responsible for ensuring the sum equals 100; buyers SHOULD validate this before execution.',
            min_length=1,
        ),
    ]
    expires_at: Annotated[
        AwareDatetime | None,
        Field(
            description='When this proposal expires and can no longer be executed. After expiration, referenced products or pricing may no longer be available.'
        ),
    ] = None
    total_budget_guidance: Annotated[
        TotalBudgetGuidance | None, Field(description='Optional budget guidance for this proposal')
    ] = None
    brief_alignment: Annotated[
        str | None,
        Field(description='Explanation of how this proposal aligns with the campaign brief'),
    ] = None
    forecast: Annotated[
        delivery_forecast.DeliveryForecast | None,
        Field(
            description='Aggregate forecasted delivery metrics for the entire proposal. When both proposal-level and allocation-level forecasts are present, the proposal-level forecast is authoritative for total delivery estimation.'
        ),
    ] = None
    ext: ext_1.ExtensionObject | None = None
