# generated by datamodel-codegen:
#   filename:  core/show_distribution.json
#   timestamp: 2026-03-16T00:33:16+00:00

from __future__ import annotations

from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import ConfigDict, Field

from ..enums import distribution_identifier_type


class Identifier(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Annotated[
        distribution_identifier_type.DistributionIdentifierType,
        Field(description='Type of distribution identifier'),
    ]
    value: Annotated[str, Field(description='The identifier value')]


class ShowDistribution(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    publisher_domain: Annotated[
        str,
        Field(
            description="Domain of the publisher platform where the show is distributed (e.g., 'youtube.com', 'spotify.com')"
        ),
    ]
    identifiers: Annotated[
        list[Identifier],
        Field(
            description='Platform-specific identifiers for the show on this publisher', min_length=1
        ),
    ]
