# generated by datamodel-codegen:
#   filename:  core/show.json
#   timestamp: 2026-03-16T00:33:16+00:00

from __future__ import annotations

from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import ConfigDict, Field

from ..enums import production_quality as production_quality_1
from ..enums import show_cadence, show_relationship, show_status
from . import content_rating as content_rating_1
from . import ext as ext_1
from . import show_distribution
from . import talent as talent_1


class RelatedShow(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    show_id: Annotated[
        str, Field(description="The related show's show_id within this seller's response")
    ]
    relationship: Annotated[
        show_relationship.ShowRelationship, Field(description='How the shows are related')
    ]


class Show(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    show_id: Annotated[
        str,
        Field(
            description='Seller-assigned identifier for this show. Unique within a single get_products response but not globally unique across sellers. Use distribution identifiers for cross-seller matching.'
        ),
    ]
    name: Annotated[str, Field(description='Human-readable show name')]
    description: Annotated[str | None, Field(description='What the show is about')] = None
    genre: Annotated[
        list[str] | None,
        Field(
            description='Genre tags. When genre_taxonomy is present, values are taxonomy IDs (e.g., IAB Content Taxonomy 3.0 codes). Otherwise free-form.'
        ),
    ] = None
    genre_taxonomy: Annotated[
        str | None,
        Field(
            description="Taxonomy system for genre values (e.g., 'iab_content_3.0'). When present, genre values should be valid taxonomy IDs. Recommended for machine-readable brand safety evaluation."
        ),
    ] = None
    language: Annotated[
        str | None, Field(description="Primary language (BCP 47 tag, e.g., 'en', 'es-MX')")
    ] = None
    content_rating: Annotated[
        content_rating_1.ContentRating | None,
        Field(
            description='Baseline content rating for the show. Individual episodes may override this.'
        ),
    ] = None
    cadence: Annotated[
        show_cadence.ShowCadence | None,
        Field(description='How frequently the show releases new episodes'),
    ] = None
    season: Annotated[
        str | None,
        Field(
            description="Current or most recent season identifier (e.g., '3', '2026', 'spring_2026'). A lightweight label — not a full season object."
        ),
    ] = None
    status: Annotated[
        show_status.ShowStatus | None, Field(description='Lifecycle status of the show')
    ] = None
    production_quality: Annotated[
        production_quality_1.ProductionQuality | None,
        Field(
            description='Production quality tier. Seller-declared. Maps to OpenRTB content.prodq (professional=1, prosumer=2, ugc=3).'
        ),
    ] = None
    talent: Annotated[
        list[talent_1.Talent] | None,
        Field(
            description='Hosts, recurring cast, creators associated with the show. Each talent entry may include a brand_url linking to their brand.json identity.'
        ),
    ] = None
    distribution: Annotated[
        list[show_distribution.ShowDistribution] | None,
        Field(
            description='Where this show is distributed. Each entry maps the show to a publisher platform with platform-specific identifiers. Shows SHOULD include at least one platform-independent identifier (imdb_id, gracenote_id, eidr_id) when available.'
        ),
    ] = None
    related_shows: Annotated[
        list[RelatedShow] | None,
        Field(
            description='Relationships to other shows (spin-offs, companion shows, etc.). Each entry references another show by show_id within the same response.'
        ),
    ] = None
    ext: ext_1.ExtensionObject | None = None
