# generated by datamodel-codegen:
#   filename:  core/start_timing.json
#   timestamp: 2026-04-16T02:55:59+00:00

from __future__ import annotations

from typing import Any, Annotated

from pydantic import AwareDatetime, Field, RootModel


class StartTiming(RootModel[str | AwareDatetime]):
    root: Annotated[
        str | AwareDatetime,
        Field(
            description="Campaign start timing: 'asap' or ISO 8601 date-time", title='Start Timing'
        ),
    ]

    def __getattr__(self, name: str) -> Any:
        """Proxy attribute access to the wrapped type."""
        if name.startswith('_'):
            raise AttributeError(name)
        return getattr(self.root, name)
