# generated by datamodel-codegen:
#   filename:  core/talent.json
#   timestamp: 2026-03-16T00:33:16+00:00

from __future__ import annotations

from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import AnyUrl, ConfigDict, Field

from ..enums import talent_role


class Talent(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    role: Annotated[
        talent_role.TalentRole, Field(description='Role of this person on the show or episode')
    ]
    name: Annotated[str, Field(description="Person's name as credited on the show")]
    brand_url: Annotated[
        AnyUrl | None,
        Field(
            description="URL to this person's brand.json entry. Enables buyer agents to evaluate the talent's brand identity and associations."
        ),
    ] = None
