# generated by datamodel-codegen:
#   filename:  core/vendor_pricing_option.json
#   timestamp: 2026-04-18T19:31:26+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Annotated, Literal

from adcp.types.base import AdCPBaseModel
from pydantic import ConfigDict, Field, RootModel

from . import ext as ext_1


class VendorPricingOption1(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    model: Literal['cpm']
    cpm: Annotated[float, Field(description='Cost per thousand impressions', ge=0.0)]
    currency: Annotated[str, Field(description='ISO 4217 currency code', pattern='^[A-Z]{3}$')]
    ext: ext_1.ExtensionObject | None = None


class VendorPricingOption2(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    model: Literal['percent_of_media']
    percent: Annotated[
        float, Field(description='Percentage of media spend, e.g. 15 = 15%', ge=0.0, le=100.0)
    ]
    max_cpm: Annotated[
        float | None,
        Field(
            description='Optional CPM cap. When set, the effective charge is min(percent × media_spend_per_mille, max_cpm).',
            ge=0.0,
        ),
    ] = None
    currency: Annotated[
        str,
        Field(description='ISO 4217 currency code for the resulting charge', pattern='^[A-Z]{3}$'),
    ]
    ext: ext_1.ExtensionObject | None = None


class Period(Enum):
    monthly = 'monthly'
    quarterly = 'quarterly'
    annual = 'annual'
    campaign = 'campaign'


class VendorPricingOption3(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    model: Literal['flat_fee']
    amount: Annotated[float, Field(description='Fixed charge for the billing period', ge=0.0)]
    period: Annotated[Period, Field(description='Billing period for the flat fee.')]
    currency: Annotated[str, Field(description='ISO 4217 currency code', pattern='^[A-Z]{3}$')]
    ext: ext_1.ExtensionObject | None = None


class VendorPricingOption4(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    model: Literal['per_unit']
    unit: Annotated[
        str,
        Field(
            description="What is counted — e.g. 'format', 'image', 'token', 'variant', 'render', 'evaluation'."
        ),
    ]
    unit_price: Annotated[float, Field(description='Cost per one unit', ge=0.0)]
    currency: Annotated[str, Field(description='ISO 4217 currency code', pattern='^[A-Z]{3}$')]
    ext: ext_1.ExtensionObject | None = None


class VendorPricingOption5(AdCPBaseModel):
    pricing_option_id: Annotated[
        str,
        Field(
            description='Opaque identifier for this pricing option, unique within the vendor agent. Pass this in report_usage to identify which pricing option was applied.'
        ),
    ]


class VendorPricingOption6(VendorPricingOption1, VendorPricingOption5):
    pass


class VendorPricingOption7(VendorPricingOption2, VendorPricingOption5):
    pass


class VendorPricingOption8(VendorPricingOption3, VendorPricingOption5):
    pass


class VendorPricingOption9(VendorPricingOption4, VendorPricingOption5):
    pass


class VendorPricingOption(
    RootModel[
        VendorPricingOption6 | VendorPricingOption7 | VendorPricingOption8 | VendorPricingOption9
    ]
):
    root: Annotated[
        VendorPricingOption6 | VendorPricingOption7 | VendorPricingOption8 | VendorPricingOption9,
        Field(
            description='A pricing option offered by a vendor agent (signals, creative, governance). Combines pricing_option_id with the pricing model fields. Pass pricing_option_id in report_usage for billing verification. All vendor discovery responses return pricing_options as an array — vendors may offer multiple options (volume tiers, context-specific rates, different models per product line).',
            title='Vendor Pricing Option',
        ),
    ]

    def __getattr__(self, name: str) -> Any:
        """Proxy attribute access to the wrapped type."""
        if name.startswith('_'):
            raise AttributeError(name)
        return getattr(self.root, name)
