# generated by datamodel-codegen:
#   filename:  bundled/property/delete_property_list_response.json
#   timestamp: 2026-04-22T04:27:52+00:00

from __future__ import annotations

from typing import Annotated, Any

from adcp.types.base import AdCPBaseModel
from pydantic import ConfigDict, Field


class DeletePropertyListResponse(AdCPBaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    deleted: Annotated[bool, Field(description="Whether the list was successfully deleted")]
    list_id: Annotated[str, Field(description="ID of the deleted list")]
    context: Annotated[
        dict[str, Any] | None,
        Field(
            description="Opaque correlation data that is echoed unchanged in responses. Used for internal tracking, UI session IDs, trace IDs, and other caller-specific identifiers that don't affect protocol behavior. Context data is never parsed by AdCP agents - it's simply preserved and returned.",
            title="Context Object",
        ),
    ] = None
    ext: Annotated[
        dict[str, Any] | None,
        Field(
            description="Extension object for platform-specific, vendor-namespaced parameters. Extensions are always optional and must be namespaced under a vendor/platform key (e.g., ext.gam, ext.roku). Used for custom capabilities, partner-specific configuration, and features being proposed for standardization.",
            title="Extension Object",
        ),
    ] = None
