# generated by datamodel-codegen:
#   filename:  bundled/property/validate_property_delivery_request.json
#   timestamp: 2026-04-18T19:31:26+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any

from adcp.types.base import AdCPBaseModel
from pydantic import AnyUrl, ConfigDict, Field


class Type(Enum):
    domain = 'domain'
    subdomain = 'subdomain'
    network_id = 'network_id'
    ios_bundle = 'ios_bundle'
    android_package = 'android_package'
    apple_app_store_id = 'apple_app_store_id'
    google_play_id = 'google_play_id'
    roku_store_id = 'roku_store_id'
    fire_tv_asin = 'fire_tv_asin'
    samsung_app_id = 'samsung_app_id'
    apple_tv_bundle = 'apple_tv_bundle'
    bundle_id = 'bundle_id'
    venue_id = 'venue_id'
    screen_id = 'screen_id'
    openooh_venue_type = 'openooh_venue_type'
    rss_url = 'rss_url'
    apple_podcast_id = 'apple_podcast_id'
    spotify_collection_id = 'spotify_collection_id'
    podcast_guid = 'podcast_guid'
    station_id = 'station_id'
    facility_id = 'facility_id'


class Identifier(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Annotated[
        Type,
        Field(
            description='Type of identifier',
            examples=[
                'domain',
                'ios_bundle',
                'venue_id',
                'apple_podcast_id',
                'station_id',
                'facility_id',
            ],
            title='Property Identifier Types',
        ),
    ]
    value: Annotated[
        str,
        Field(
            description="The identifier value. For domain type: 'example.com' matches base domain plus www and m subdomains; 'edition.example.com' matches that specific subdomain; '*.example.com' matches ALL subdomains but NOT base domain"
        ),
    ]


class Record(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    identifier: Annotated[
        Identifier,
        Field(
            description='The property identifier where impressions were delivered',
            title='Identifier',
        ),
    ]
    impressions: Annotated[
        int, Field(description='Number of impressions delivered to this identifier', ge=0)
    ]
    record_id: Annotated[
        str | None,
        Field(
            description='Optional client-provided ID for correlating results back to source data'
        ),
    ] = None
    sales_agent_url: Annotated[
        AnyUrl | None,
        Field(
            description="URL of the sales agent that sold this inventory. If provided, authorization is validated against the property's adagents.json."
        ),
    ] = None
    ext: Annotated[
        dict[str, Any] | None,
        Field(
            description='Extension object for platform-specific, vendor-namespaced parameters. Extensions are always optional and must be namespaced under a vendor/platform key (e.g., ext.gam, ext.roku). Used for custom capabilities, partner-specific configuration, and features being proposed for standardization.',
            title='Extension Object',
        ),
    ] = None


class ValidatePropertyDeliveryRequest(AdCPBaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    adcp_major_version: Annotated[
        int | None,
        Field(
            description="The AdCP major version the buyer's payloads conform to. Sellers validate against their supported major_versions and return VERSION_UNSUPPORTED if unsupported. When omitted, the seller assumes its highest supported version.",
            ge=1,
            le=99,
        ),
    ] = None
    list_id: Annotated[str, Field(description='ID of the property list to validate against')]
    records: Annotated[
        list[Record],
        Field(
            description='Delivery records to validate. Each record represents impressions delivered to a property identifier.',
            max_length=10000,
            min_length=1,
        ),
    ]
    include_compliant: Annotated[
        bool | None,
        Field(
            description='Include compliant records in results (default: only return non_compliant, unmodeled, and unidentified)'
        ),
    ] = False
    context: Annotated[
        dict[str, Any] | None,
        Field(
            description="Opaque correlation data that is echoed unchanged in responses. Used for internal tracking, UI session IDs, trace IDs, and other caller-specific identifiers that don't affect protocol behavior. Context data is never parsed by AdCP agents - it's simply preserved and returned.",
            title='Context Object',
        ),
    ] = None
    ext: Annotated[
        dict[str, Any] | None,
        Field(
            description='Extension object for platform-specific, vendor-namespaced parameters. Extensions are always optional and must be namespaced under a vendor/platform key (e.g., ext.gam, ext.roku). Used for custom capabilities, partner-specific configuration, and features being proposed for standardization.',
            title='Extension Object',
        ),
    ] = None
