# generated by datamodel-codegen:
#   filename:  manifest.json
#   timestamp: 2026-10-04T18:54:18+00:00

from __future__ import annotations

from typing import Any

from pydantic import RootModel


class Model(RootModel[Any]):
    root: Any


__all__ = [
    "Model",
]
