"""Types the AdCP ``media_buy`` schemas declare.

Importing from the domain says which variant you mean, where the flat
``adcp.types`` namespace can only bind one class per name:

    from adcp.types.domains.media_buy import <Type>

A type this domain declares in more than one schema carries the defining
file in its name (``CreativeFromListCreativesResponse``); everything else
keeps the name codegen gave it.

Auto-generated from the generated_poc module tree. DO NOT EDIT MANUALLY.
Generation date: 2026-10-03 04:37:13 UTC
"""

# ruff: noqa: E501, I001
from __future__ import annotations

from adcp.types.generated_poc.media_buy.accept_proposal_async_response_input_required import (
    AcceptProposalInputRequired,
)
from adcp.types.generated_poc.media_buy.accept_proposal_async_response_submitted import (
    AcceptProposalSubmitted,
)
from adcp.types.generated_poc.media_buy.accept_proposal_async_response_working import (
    AcceptProposalWorking,
)
from adcp.types.generated_poc.media_buy.accept_proposal_request import (
    AcceptProposalRequest,
    IoAcceptance as IoAcceptanceFromAcceptProposalRequest,
    Opportunity as OpportunityFromAcceptProposalRequest,
    Status as StatusFromAcceptProposalRequest,
    TotalBudget as TotalBudgetFromAcceptProposalRequest,
)
from adcp.types.generated_poc.media_buy.accept_proposal_response import (
    AcceptProposalResponse,
    AcceptProposalResponse1,
    AcceptProposalResponse2,
    AcceptProposalResponse3,
    AcceptProposalResponse4,
    AcceptProposalResponse5,
    AcceptProposalResponse6,
    AcceptProposalResponse7,
    AcceptedProposal as AcceptedProposalFromAcceptProposalResponse,
    Code as CodeFromAcceptProposalResponse,
    ProposalStatus as ProposalStatusFromAcceptProposalResponse,
    PurchaseBinding as PurchaseBindingFromAcceptProposalResponse,
    Warning as WarningFromAcceptProposalResponse,
)
from adcp.types.generated_poc.media_buy.acceptance_context import (
    AcceptanceContext,
    AdvertiserJurisdiction,
    AdvertiserRole as AdvertiserRoleFromAcceptanceContext,
    DeliveryJurisdiction,
    Subject,
    SubjectFacet as SubjectFacetFromAcceptanceContext,
)
from adcp.types.generated_poc.media_buy.acceptance_policy_catalog import AcceptancePolicyCatalog
from adcp.types.generated_poc.media_buy.acceptance_policy_profile import (
    AcceptancePolicyProfile,
    AppliesToEnum as AppliesToEnumFromAcceptancePolicyProfile,
    Coverage,
    Jurisdiction as JurisdictionFromAcceptancePolicyProfile,
    JurisdictionGroup as JurisdictionGroupFromAcceptancePolicyProfile,
    PolicyRef,
    RegionAliase,
    Scope as ScopeFromAcceptancePolicyProfile,
    SubjectCategory,
)
from adcp.types.generated_poc.media_buy.acceptance_policy_profile_ref import (
    RegistryAcceptancePolicyProfileReference,
)
from adcp.types.generated_poc.media_buy.acceptance_policy_requirement import (
    AcceptancePolicyRequirement,
    AcceptancePolicyRequirement1,
    AcceptancePolicyRequirement10,
    AcceptancePolicyRequirement11,
    AcceptancePolicyRequirement12,
    AcceptancePolicyRequirement13,
    AcceptancePolicyRequirement14,
    AcceptancePolicyRequirement15,
    AcceptancePolicyRequirement16,
    AcceptancePolicyRequirement17,
    AcceptancePolicyRequirement2,
    AcceptancePolicyRequirement3,
    AcceptancePolicyRequirement4,
    AcceptancePolicyRequirement5,
    AcceptancePolicyRequirement6,
    AcceptancePolicyRequirement7,
    AcceptancePolicyRequirement8,
    AcceptancePolicyRequirement9,
    Criterion,
    FormatId,
)
from adcp.types.generated_poc.media_buy.acceptance_policy_rule import (
    AcceptancePolicyRule,
    AdvertiserRole as AdvertiserRoleFromAcceptancePolicyRule,
    AppliesToEnum as AppliesToEnumFromAcceptancePolicyRule,
    Disposition,
    Jurisdiction as JurisdictionFromAcceptancePolicyRule,
    JurisdictionGroup as JurisdictionGroupFromAcceptancePolicyRule,
    PolicyId as PolicyIdFromAcceptancePolicyRule,
    SubjectFacet as SubjectFacetFromAcceptancePolicyRule,
)
from adcp.types.generated_poc.media_buy.build_creative_async_response_input_required import (
    BuildCreativeInputRequired,
    Reason as ReasonFromBuildCreativeAsyncResponseInputRequired,
)
from adcp.types.generated_poc.media_buy.build_creative_async_response_submitted import (
    BuildCreativeSubmitted,
)
from adcp.types.generated_poc.media_buy.build_creative_async_response_working import (
    BuildCreativeWorking,
)
from adcp.types.generated_poc.media_buy.build_creative_request import (
    BuildCreativeRequest,
    Dimension,
    KeepMode,
    MaxSpend,
    Mode,
    PreviewInput,
    SignalCondition,
    SignalCondition1,
    SignalCondition2,
    SignalCondition3,
    SignalCondition4,
    SignalCondition5,
    SignalCondition6,
    SignalCondition7,
    TargetCapabilityId,
    VariantAxis,
)
from adcp.types.generated_poc.media_buy.build_creative_response import (
    BuildCreativeResponse,
    BuildCreativeResponse1,
    BuildCreativeResponse2,
    BuildCreativeResponse3,
    BuildCreativeResponse4,
    BuildCreativeResponse5,
    BuildCreativeResponse6,
    CatalogItemRef,
    Creative as CreativeFromBuildCreativeResponse,
    Estimate,
    Eval,
    Input,
    Input2,
    PerLeaf,
    Preview,
    Preview2,
    Preview3,
    Preview4,
    Variant,
)
from adcp.types.generated_poc.media_buy.buy_products_async_response_input_required import (
    BuyProductsInputRequired,
)
from adcp.types.generated_poc.media_buy.buy_products_async_response_submitted import (
    BuyProductsSubmitted,
)
from adcp.types.generated_poc.media_buy.buy_products_async_response_working import (
    BuyProductsWorking,
)
from adcp.types.generated_poc.media_buy.buy_products_request import (
    BuyProductsRequest,
    Opportunity as OpportunityFromBuyProductsRequest,
    Status as StatusFromBuyProductsRequest,
    TotalBudget as TotalBudgetFromBuyProductsRequest,
)
from adcp.types.generated_poc.media_buy.buy_products_response import (
    AcceptedProposal as AcceptedProposalFromBuyProductsResponse,
    BuyProductsResponse,
    BuyProductsResponse1,
    BuyProductsResponse2,
    BuyProductsResponse3,
    BuyProductsResponse4,
    BuyProductsResponse5,
    BuyProductsResponse6,
    BuyProductsResponse7,
    Code as CodeFromBuyProductsResponse,
    ProposalStatus as ProposalStatusFromBuyProductsResponse,
    PurchaseBinding as PurchaseBindingFromBuyProductsResponse,
    Warning as WarningFromBuyProductsResponse,
)
from adcp.types.generated_poc.media_buy.change_term import (
    AllowedStatus,
    Condition,
    MediaBuyChangeTerm,
)
from adcp.types.generated_poc.media_buy.change_term_constraints import (
    MediaBuyChangeTermConstraints,
    MediaBuyChangeTermConstraints1,
    MediaBuyChangeTermConstraints2,
    MediaBuyChangeTermConstraints3,
    MediaBuyChangeTermConstraints4,
    Money,
)
from adcp.types.generated_poc.media_buy.commercial_terms import (
    CancellationTerms,
    CommercialTerms,
    Fee,
    ReportingCommitment,
    TotalBudget as TotalBudgetFromCommercialTerms,
)
from adcp.types.generated_poc.media_buy.control_media_buy_async_response_input_required import (
    ControlMediaBuyInputRequired,
)
from adcp.types.generated_poc.media_buy.control_media_buy_async_response_submitted import (
    ControlMediaBuySubmitted,
)
from adcp.types.generated_poc.media_buy.control_media_buy_async_response_working import (
    ControlMediaBuyWorking,
)
from adcp.types.generated_poc.media_buy.control_media_buy_request import (
    ControlMediaBuyRequest,
    TotalBudget as TotalBudgetFromControlMediaBuyRequest,
)
from adcp.types.generated_poc.media_buy.control_media_buy_response import (
    AffectedPackageId,
    Code as CodeFromControlMediaBuyResponse,
    ControlMediaBuyResponse,
    ControlMediaBuyResponse1,
    ControlMediaBuyResponse2,
    ControlMediaBuyResponse3,
    Warning as WarningFromControlMediaBuyResponse,
)
from adcp.types.generated_poc.media_buy.create_media_buy_async_response_input_required import (
    CreateMediaBuyInputRequired,
    Reason as ReasonFromCreateMediaBuyAsyncResponseInputRequired,
)
from adcp.types.generated_poc.media_buy.create_media_buy_async_response_submitted import (
    CreateMediaBuySubmitted,
)
from adcp.types.generated_poc.media_buy.create_media_buy_async_response_working import (
    CreateMediaBuyWorking,
)
from adcp.types.generated_poc.media_buy.create_media_buy_request import (
    ArtifactWebhook,
    Authentication,
    BatchFrequency,
    CreateMediaBuyRequest,
    DeliveryMode,
    IoAcceptance as IoAcceptanceFromCreateMediaBuyRequest,
    Opportunity as OpportunityFromCreateMediaBuyRequest,
    Status as StatusFromCreateMediaBuyRequest,
    TotalBudget as TotalBudgetFromCreateMediaBuyRequest,
)
from adcp.types.generated_poc.media_buy.create_media_buy_response import (
    CreateMediaBuyResponse,
    CreateMediaBuyResponse1,
    CreateMediaBuyResponse2,
    CreateMediaBuyResponse3,
)
from adcp.types.generated_poc.media_buy.decline_proposals_async_response_input_required import (
    DeclineProposalsInputRequired,
)
from adcp.types.generated_poc.media_buy.decline_proposals_async_response_submitted import (
    DeclineProposalsSubmitted,
)
from adcp.types.generated_poc.media_buy.decline_proposals_async_response_working import (
    DeclineProposalsWorking,
)
from adcp.types.generated_poc.media_buy.decline_proposals_request import DeclineProposalsRequest
from adcp.types.generated_poc.media_buy.decline_proposals_response import (
    DeclineProposalsResponse,
    DeclineProposalsResponse1,
    DeclineProposalsResponse2,
    Outcome as OutcomeFromDeclineProposalsResponse,
    Results as ResultsFromDeclineProposalsResponse,
    Results1,
    Results2,
    Results3,
    Results4,
    Results5,
)
from adcp.types.generated_poc.media_buy.get_media_buy_delivery_request import (
    AttributionWindow,
    Audience as AudienceFromGetMediaBuyDeliveryRequest,
    CatalogItem,
    Creative as CreativeFromGetMediaBuyDeliveryRequest,
    Demographic,
    DevicePlatform,
    DeviceType,
    Format,
    Geo,
    GetMediaBuyDeliveryRequest,
    Keyword,
    Placement,
    ReportingDimensions,
    Spot,
    StatusFilter as StatusFilterFromGetMediaBuyDeliveryRequest,
)
from adcp.types.generated_poc.media_buy.get_media_buy_delivery_response import (
    AggregatedTotals,
    ByAudienceItem,
    ByDemographicItem,
    ByDevicePlatformItem,
    ByDeviceTypeItem,
    ByFormatItem,
    ByPackageItem as ByPackageItemFromGetMediaBuyDeliveryResponse,
    ByPackageItem1,
    BySpotItem,
    DailyBreakdownItem,
    DailyBreakdownItem1,
    GetMediaBuyDeliveryResponse,
    MediaBuyDelivery as MediaBuyDeliveryFromGetMediaBuyDeliveryResponse,
    NotificationType as NotificationTypeFromGetMediaBuyDeliveryResponse,
    ReportingPeriod as ReportingPeriodFromGetMediaBuyDeliveryResponse,
    ReportingRevisionBinding,
    Status as StatusFromGetMediaBuyDeliveryResponse,
    Totals as TotalsFromGetMediaBuyDeliveryResponse,
    Window,
)
from adcp.types.generated_poc.media_buy.get_media_buys_request import (
    GetMediaBuysRequest,
    StatusFilter as StatusFilterFromGetMediaBuysRequest,
)
from adcp.types.generated_poc.media_buy.get_media_buys_response import (
    AcceptedProposal as AcceptedProposalFromGetMediaBuysResponse,
    Cancellation,
    Cancellation1,
    CreativeApproval,
    GetMediaBuysResponse,
    HistoryItem,
    Indicator,
    Indicator1,
    Indicator2,
    IndicatorTypesEvaluatedEnum,
    IndicatorTypesEvaluatedEnum1,
    IndicatorTypesEvaluatedEnum2,
    MediaBuy,
    Package,
    ProposalStatus as ProposalStatusFromGetMediaBuysResponse,
    Snapshot,
)
from adcp.types.generated_poc.media_buy.get_products_async_response_input_required import (
    GetProductsInputRequired,
    Reason as ReasonFromGetProductsAsyncResponseInputRequired,
)
from adcp.types.generated_poc.media_buy.get_products_async_response_submitted import (
    GetProductsSubmitted,
)
from adcp.types.generated_poc.media_buy.get_products_async_response_working import (
    GetProductsWorking,
)
from adcp.types.generated_poc.media_buy.get_products_rejected import (
    GetProductsRejected,
    Suggestion as SuggestionFromGetProductsRejected,
)
from adcp.types.generated_poc.media_buy.get_products_request import (
    Action as ActionFromGetProductsRequest,
    Action9,
    BuyingMode,
    Field1,
    Fields,
    GetProductsRequest,
    Refine,
    Refine1,
    Refine2,
    Refine3,
)
from adcp.types.generated_poc.media_buy.get_products_response import (
    CacheScope as CacheScopeFromGetProductsResponse,
    ExcludedBy,
    Extensions,
    FilterDiagnostics,
    GetProductsResponse,
    IncompleteItem as IncompleteItemFromGetProductsResponse,
    RefinementApplied,
    RefinementApplied1,
    RefinementApplied2,
    RefinementApplied3,
    Scope as ScopeFromGetProductsResponse,
    Semantics,
    Status as StatusFromGetProductsResponse,
    Suggestion as SuggestionFromGetProductsResponse,
)
from adcp.types.generated_poc.media_buy.get_products_targeting_resolution import (
    ProductDiscoveryTargetingResolution,
)
from adcp.types.generated_poc.media_buy.get_reporting_status_request import (
    DeliveryConfigId,
    GetReportingStatusRequest,
    Period,
    ReportingStatusView,
)
from adcp.types.generated_poc.media_buy.get_reporting_status_response import (
    DeliveryConfigGeneration,
    GetReportingStatusResponse,
    ObligationCounts,
    Scope as ScopeFromGetReportingStatusResponse,
    Status as StatusFromGetReportingStatusResponse,
)
from adcp.types.generated_poc.media_buy.legacy_purchase_continuation_input import (
    AcceptedLoss,
    CompatibilityPurchaseCoordinatorInput,
    SelectedProductId,
)
from adcp.types.generated_poc.media_buy.list_creative_formats_request import (
    ListCreativeFormatsRequest,
)
from adcp.types.generated_poc.media_buy.list_creative_formats_response import (
    CreativeAgent,
    ListCreativeFormatsResponse,
    Source as SourceFromListCreativeFormatsResponse,
)
from adcp.types.generated_poc.media_buy.list_products_request import ListProductsRequest
from adcp.types.generated_poc.media_buy.list_products_response import (
    CacheScope as CacheScopeFromListProductsResponse,
    IncompleteItem as IncompleteItemFromListProductsResponse,
    IncompleteItem3,
    ListProductsResponse,
    ListProductsResponse1,
    ListProductsResponse2,
    Outcome as OutcomeFromListProductsResponse,
    Scope as ScopeFromListProductsResponse,
)
from adcp.types.generated_poc.media_buy.log_event_request import LogEventRequest
from adcp.types.generated_poc.media_buy.log_event_response import (
    LogEventResponse,
    LogEventResponse1,
    LogEventResponse2,
    PartialFailure,
)
from adcp.types.generated_poc.media_buy.media_buy_commitment_response import (
    AcceptedProposal as AcceptedProposalFromMediaBuyCommitmentResponse,
    Code as CodeFromMediaBuyCommitmentResponse,
    MediaBuyCommitmentResponse,
    MediaBuyCommitmentResponse1,
    MediaBuyCommitmentResponse2,
    MediaBuyCommitmentResponse3,
    ProposalStatus as ProposalStatusFromMediaBuyCommitmentResponse,
    PurchaseBinding as PurchaseBindingFromMediaBuyCommitmentResponse,
    Warning as WarningFromMediaBuyCommitmentResponse,
)
from adcp.types.generated_poc.media_buy.media_buy_delivery_webhook_result import (
    ByPackageItem as ByPackageItemFromMediaBuyDeliveryWebhookResult,
    MediaBuyDelivery as MediaBuyDeliveryFromMediaBuyDeliveryWebhookResult,
    MediaBuyDeliveryWebhookResult,
    NotificationType as NotificationTypeFromMediaBuyDeliveryWebhookResult,
    ReportingPeriod as ReportingPeriodFromMediaBuyDeliveryWebhookResult,
    Status as StatusFromMediaBuyDeliveryWebhookResult,
    Totals as TotalsFromMediaBuyDeliveryWebhookResult,
)
from adcp.types.generated_poc.media_buy.outcome_target import Goal, Goal1, OutcomeTarget
from adcp.types.generated_poc.media_buy.package_control import (
    CatalogId as CatalogIdFromPackageControl,
    PackageControl,
)
from adcp.types.generated_poc.media_buy.package_request import (
    CommittedMetrics,
    CommittedMetrics1,
    CommittedMetrics2,
    PackageRequest,
    Qualifier,
)
from adcp.types.generated_poc.media_buy.package_update import (
    KeywordTargetsAddItem,
    KeywordTargetsRemoveItem,
    NegativeKeywordsAddItem,
    NegativeKeywordsRemoveItem,
    PackageUpdate,
)
from adcp.types.generated_poc.media_buy.product_discovery_criteria import (
    PolicyId as PolicyIdFromProductDiscoveryCriteria,
    ProductDiscoveryCriteria,
    ProductId as ProductIdFromProductDiscoveryCriteria,
)
from adcp.types.generated_poc.media_buy.product_fields import (
    ProductResponseField,
    ProductResponseFields,
)
from adcp.types.generated_poc.media_buy.product_purchase import (
    AgencyEstimateNumber,
    AudienceEvidencePins,
    Bidding,
    Budget,
    CatalogId as CatalogIdFromProductPurchase,
    CatalogIds,
    Context,
    DailyBudgetCap,
    EndTime,
    Ext,
    FormatOptionRefs,
    MinSpendTarget,
    OptimizationGoals,
    Pacing,
    PerformanceStandards,
    Pricing,
    PricingOptionId,
    ProductId as ProductIdFromProductPurchase,
    ProductPurchase,
    StartTime,
)
from adcp.types.generated_poc.media_buy.product_purchase_input import ProductPurchaseInput
from adcp.types.generated_poc.media_buy.product_refinement import (
    Action as ActionFromProductRefinement,
    Action11,
    ProductRefinementRequests,
    ProductRefinementRequests1,
    ProductRefinementRequests2,
    ProductRefinementRequests3,
    ProductRefinementRequests4,
)
from adcp.types.generated_poc.media_buy.proposal_budget_constraint import ProposalBudgetConstraint
from adcp.types.generated_poc.media_buy.proposal_decline import ProposalDecline
from adcp.types.generated_poc.media_buy.proposal_refinement import (
    Action as ActionFromProposalRefinement,
    Alternatives,
    ChangeKind,
    Constraints,
    Constraints1,
    Constraints2,
    Constraints3,
    Constraints4,
    Constraints5,
    Constraints6,
    Constraints7,
    Cpm,
    Flight,
    Impressions,
    ProposalRefinement,
    ProposalRefinement2,
    ProposalRefinement3,
    ProposalRefinement4,
    ProposalRefinement5,
    ProposalRefinement6,
    ProposalRefinement7,
    ProposalRefinement8,
    ProposalRefinement9,
)
from adcp.types.generated_poc.media_buy.provide_performance_feedback_request import (
    ProvidePerformanceFeedbackRequest,
)
from adcp.types.generated_poc.media_buy.provide_performance_feedback_response import (
    ProvidePerformanceFeedbackResponse,
    ProvidePerformanceFeedbackResponse1,
    ProvidePerformanceFeedbackResponse2,
)
from adcp.types.generated_poc.media_buy.refine_proposals_async_response_input_required import (
    RefineProposalsInputRequired,
)
from adcp.types.generated_poc.media_buy.refine_proposals_async_response_submitted import (
    RefineProposalsSubmitted,
)
from adcp.types.generated_poc.media_buy.refine_proposals_async_response_working import (
    RefineProposalsWorking,
)
from adcp.types.generated_poc.media_buy.refine_proposals_request import (
    RefineProposalsRequest,
    Refinements,
)
from adcp.types.generated_poc.media_buy.refine_proposals_response import (
    Outcome as OutcomeFromRefineProposalsResponse,
    Proposal as ProposalFromRefineProposalsResponse,
    Proposal2,
    Proposal3,
    Proposal4,
    Proposal5,
    Proposal6,
    ProposalKind,
    ProposalStatus as ProposalStatusFromRefineProposalsResponse,
    RefineProposalsResponse,
    RefineProposalsResponse1,
    RefineProposalsResponse2,
    Results as ResultsFromRefineProposalsResponse,
    Results10,
    Results11,
    Results12,
    Results14,
    Results15,
    Results16,
    Results17,
    Results18,
    Results8,
    Results9,
    Status as StatusFromRefineProposalsResponse,
    Suggestion as SuggestionFromRefineProposalsResponse,
    TotalBudgetGuidance,
    UnsatisfiedConstraint,
)
from adcp.types.generated_poc.media_buy.request_proposals_async_response_input_required import (
    RequestProposalsInputRequired,
)
from adcp.types.generated_poc.media_buy.request_proposals_async_response_submitted import (
    RequestProposalsSubmitted,
)
from adcp.types.generated_poc.media_buy.request_proposals_async_response_working import (
    RequestProposalsWorking,
)
from adcp.types.generated_poc.media_buy.request_proposals_request import (
    Opportunity as OpportunityFromRequestProposalsRequest,
    RequestProposalsRequest,
    Status as StatusFromRequestProposalsRequest,
)
from adcp.types.generated_poc.media_buy.request_proposals_response import (
    IncompleteItem as IncompleteItemFromRequestProposalsResponse,
    IncompleteItem5,
    IncompleteItem6,
    IncompleteItem7,
    Loss,
    Losses,
    Outcome as OutcomeFromRequestProposalsResponse,
    ProductId as ProductIdFromRequestProposalsResponse,
    Proposal as ProposalFromRequestProposalsResponse,
    ProposalStatus as ProposalStatusFromRequestProposalsResponse,
    PurchaseContinuation,
    PurchaseContinuation1,
    PurchaseContinuation2,
    PurchaseContinuation3,
    PurchaseContinuation4,
    PurchaseContinuation5,
    PurchaseContinuation6,
    PurchaseContinuation7,
    RequestProposalsResponse,
    RequestProposalsResponse1,
    RequestProposalsResponse2,
    RequestProposalsResponse3,
    RequestProposalsResponse4,
    Scope as ScopeFromRequestProposalsResponse,
    SourceAdcpVersion,
    Status as StatusFromRequestProposalsResponse,
    Suggestion as SuggestionFromRequestProposalsResponse,
)
from adcp.types.generated_poc.media_buy.sync_audiences_request import (
    Audience as AudienceFromSyncAudiencesRequest,
    AudienceType,
    SyncAudiencesRequest,
    Tag,
)
from adcp.types.generated_poc.media_buy.sync_audiences_response import (
    Audience as AudienceFromSyncAudiencesResponse,
    MatchBreakdown,
    Source as SourceFromSyncAudiencesResponse,
    SyncAudiencesResponse,
    SyncAudiencesResponse1,
    SyncAudiencesResponse2,
    SyncAudiencesResponse3,
)
from adcp.types.generated_poc.media_buy.sync_catalogs_async_response_input_required import (
    Reason as ReasonFromSyncCatalogsAsyncResponseInputRequired,
    SyncCatalogsInputRequired,
)
from adcp.types.generated_poc.media_buy.sync_catalogs_async_response_submitted import (
    SyncCatalogsSubmitted,
)
from adcp.types.generated_poc.media_buy.sync_catalogs_async_response_working import (
    SyncCatalogsWorking,
)
from adcp.types.generated_poc.media_buy.sync_catalogs_request import SyncCatalogsRequest
from adcp.types.generated_poc.media_buy.sync_catalogs_response import (
    Catalog,
    ItemIssue,
    SyncCatalogsResponse,
    SyncCatalogsResponse1,
    SyncCatalogsResponse2,
    SyncCatalogsResponse3,
)
from adcp.types.generated_poc.media_buy.sync_event_sources_request import (
    EventSource as EventSourceFromSyncEventSourcesRequest,
    SyncEventSourcesRequest,
    ValueCurrency,
)
from adcp.types.generated_poc.media_buy.sync_event_sources_response import (
    EventSource as EventSourceFromSyncEventSourcesResponse,
    Setup,
    SyncEventSourcesResponse,
    SyncEventSourcesResponse1,
    SyncEventSourcesResponse2,
)
from adcp.types.generated_poc.media_buy.sync_reporting_receipts_request import (
    SyncReportingReceiptsRequest,
)
from adcp.types.generated_poc.media_buy.sync_reporting_receipts_response import (
    Results as ResultsFromSyncReportingReceiptsResponse,
    Results20,
    Results21,
    Results22,
    Results23,
    SyncReportingReceiptsResponse,
)
from adcp.types.generated_poc.media_buy.sync_reporting_status_request import (
    SyncReportingStatusRequest,
)
from adcp.types.generated_poc.media_buy.sync_reporting_status_response import (
    Results as ResultsFromSyncReportingStatusResponse,
    Results26,
    Results27,
    SyncReportingStatusResponse,
)
from adcp.types.generated_poc.media_buy.update_media_buy_async_response_input_required import (
    Reason as ReasonFromUpdateMediaBuyAsyncResponseInputRequired,
    UpdateMediaBuyInputRequired,
)
from adcp.types.generated_poc.media_buy.update_media_buy_async_response_submitted import (
    UpdateMediaBuySubmitted,
)
from adcp.types.generated_poc.media_buy.update_media_buy_async_response_working import (
    UpdateMediaBuyWorking,
)
from adcp.types.generated_poc.media_buy.update_media_buy_request import (
    TotalBudget as TotalBudgetFromUpdateMediaBuyRequest,
    UpdateMediaBuyRequest,
)
from adcp.types.generated_poc.media_buy.update_media_buy_response import (
    UpdateMediaBuyResponse,
    UpdateMediaBuyResponse1,
    UpdateMediaBuyResponse2,
    UpdateMediaBuyResponse3,
)

# Explicit exports
__all__ = [
    "AcceptProposalInputRequired",
    "AcceptProposalRequest",
    "AcceptProposalResponse",
    "AcceptProposalResponse1",
    "AcceptProposalResponse2",
    "AcceptProposalResponse3",
    "AcceptProposalResponse4",
    "AcceptProposalResponse5",
    "AcceptProposalResponse6",
    "AcceptProposalResponse7",
    "AcceptProposalSubmitted",
    "AcceptProposalWorking",
    "AcceptanceContext",
    "AcceptancePolicyCatalog",
    "AcceptancePolicyProfile",
    "AcceptancePolicyRequirement",
    "AcceptancePolicyRequirement1",
    "AcceptancePolicyRequirement10",
    "AcceptancePolicyRequirement11",
    "AcceptancePolicyRequirement12",
    "AcceptancePolicyRequirement13",
    "AcceptancePolicyRequirement14",
    "AcceptancePolicyRequirement15",
    "AcceptancePolicyRequirement16",
    "AcceptancePolicyRequirement17",
    "AcceptancePolicyRequirement2",
    "AcceptancePolicyRequirement3",
    "AcceptancePolicyRequirement4",
    "AcceptancePolicyRequirement5",
    "AcceptancePolicyRequirement6",
    "AcceptancePolicyRequirement7",
    "AcceptancePolicyRequirement8",
    "AcceptancePolicyRequirement9",
    "AcceptancePolicyRule",
    "AcceptedLoss",
    "AcceptedProposalFromAcceptProposalResponse",
    "AcceptedProposalFromBuyProductsResponse",
    "AcceptedProposalFromGetMediaBuysResponse",
    "AcceptedProposalFromMediaBuyCommitmentResponse",
    "Action11",
    "Action9",
    "ActionFromGetProductsRequest",
    "ActionFromProductRefinement",
    "ActionFromProposalRefinement",
    "AdvertiserJurisdiction",
    "AdvertiserRoleFromAcceptanceContext",
    "AdvertiserRoleFromAcceptancePolicyRule",
    "AffectedPackageId",
    "AgencyEstimateNumber",
    "AggregatedTotals",
    "AllowedStatus",
    "Alternatives",
    "AppliesToEnumFromAcceptancePolicyProfile",
    "AppliesToEnumFromAcceptancePolicyRule",
    "ArtifactWebhook",
    "AttributionWindow",
    "AudienceEvidencePins",
    "AudienceFromGetMediaBuyDeliveryRequest",
    "AudienceFromSyncAudiencesRequest",
    "AudienceFromSyncAudiencesResponse",
    "AudienceType",
    "Authentication",
    "BatchFrequency",
    "Bidding",
    "Budget",
    "BuildCreativeInputRequired",
    "BuildCreativeRequest",
    "BuildCreativeResponse",
    "BuildCreativeResponse1",
    "BuildCreativeResponse2",
    "BuildCreativeResponse3",
    "BuildCreativeResponse4",
    "BuildCreativeResponse5",
    "BuildCreativeResponse6",
    "BuildCreativeSubmitted",
    "BuildCreativeWorking",
    "BuyProductsInputRequired",
    "BuyProductsRequest",
    "BuyProductsResponse",
    "BuyProductsResponse1",
    "BuyProductsResponse2",
    "BuyProductsResponse3",
    "BuyProductsResponse4",
    "BuyProductsResponse5",
    "BuyProductsResponse6",
    "BuyProductsResponse7",
    "BuyProductsSubmitted",
    "BuyProductsWorking",
    "BuyingMode",
    "ByAudienceItem",
    "ByDemographicItem",
    "ByDevicePlatformItem",
    "ByDeviceTypeItem",
    "ByFormatItem",
    "ByPackageItem1",
    "ByPackageItemFromGetMediaBuyDeliveryResponse",
    "ByPackageItemFromMediaBuyDeliveryWebhookResult",
    "BySpotItem",
    "CacheScopeFromGetProductsResponse",
    "CacheScopeFromListProductsResponse",
    "Cancellation",
    "Cancellation1",
    "CancellationTerms",
    "Catalog",
    "CatalogIdFromPackageControl",
    "CatalogIdFromProductPurchase",
    "CatalogIds",
    "CatalogItem",
    "CatalogItemRef",
    "ChangeKind",
    "CodeFromAcceptProposalResponse",
    "CodeFromBuyProductsResponse",
    "CodeFromControlMediaBuyResponse",
    "CodeFromMediaBuyCommitmentResponse",
    "CommercialTerms",
    "CommittedMetrics",
    "CommittedMetrics1",
    "CommittedMetrics2",
    "CompatibilityPurchaseCoordinatorInput",
    "Condition",
    "Constraints",
    "Constraints1",
    "Constraints2",
    "Constraints3",
    "Constraints4",
    "Constraints5",
    "Constraints6",
    "Constraints7",
    "Context",
    "ControlMediaBuyInputRequired",
    "ControlMediaBuyRequest",
    "ControlMediaBuyResponse",
    "ControlMediaBuyResponse1",
    "ControlMediaBuyResponse2",
    "ControlMediaBuyResponse3",
    "ControlMediaBuySubmitted",
    "ControlMediaBuyWorking",
    "Coverage",
    "Cpm",
    "CreateMediaBuyInputRequired",
    "CreateMediaBuyRequest",
    "CreateMediaBuyResponse",
    "CreateMediaBuyResponse1",
    "CreateMediaBuyResponse2",
    "CreateMediaBuyResponse3",
    "CreateMediaBuySubmitted",
    "CreateMediaBuyWorking",
    "CreativeAgent",
    "CreativeApproval",
    "CreativeFromBuildCreativeResponse",
    "CreativeFromGetMediaBuyDeliveryRequest",
    "Criterion",
    "DailyBreakdownItem",
    "DailyBreakdownItem1",
    "DailyBudgetCap",
    "DeclineProposalsInputRequired",
    "DeclineProposalsRequest",
    "DeclineProposalsResponse",
    "DeclineProposalsResponse1",
    "DeclineProposalsResponse2",
    "DeclineProposalsSubmitted",
    "DeclineProposalsWorking",
    "DeliveryConfigGeneration",
    "DeliveryConfigId",
    "DeliveryJurisdiction",
    "DeliveryMode",
    "Demographic",
    "DevicePlatform",
    "DeviceType",
    "Dimension",
    "Disposition",
    "EndTime",
    "Estimate",
    "Eval",
    "EventSourceFromSyncEventSourcesRequest",
    "EventSourceFromSyncEventSourcesResponse",
    "ExcludedBy",
    "Ext",
    "Extensions",
    "Fee",
    "Field1",
    "Fields",
    "FilterDiagnostics",
    "Flight",
    "Format",
    "FormatId",
    "FormatOptionRefs",
    "Geo",
    "GetMediaBuyDeliveryRequest",
    "GetMediaBuyDeliveryResponse",
    "GetMediaBuysRequest",
    "GetMediaBuysResponse",
    "GetProductsInputRequired",
    "GetProductsRejected",
    "GetProductsRequest",
    "GetProductsResponse",
    "GetProductsSubmitted",
    "GetProductsWorking",
    "GetReportingStatusRequest",
    "GetReportingStatusResponse",
    "Goal",
    "Goal1",
    "HistoryItem",
    "Impressions",
    "IncompleteItem3",
    "IncompleteItem5",
    "IncompleteItem6",
    "IncompleteItem7",
    "IncompleteItemFromGetProductsResponse",
    "IncompleteItemFromListProductsResponse",
    "IncompleteItemFromRequestProposalsResponse",
    "Indicator",
    "Indicator1",
    "Indicator2",
    "IndicatorTypesEvaluatedEnum",
    "IndicatorTypesEvaluatedEnum1",
    "IndicatorTypesEvaluatedEnum2",
    "Input",
    "Input2",
    "IoAcceptanceFromAcceptProposalRequest",
    "IoAcceptanceFromCreateMediaBuyRequest",
    "ItemIssue",
    "JurisdictionFromAcceptancePolicyProfile",
    "JurisdictionFromAcceptancePolicyRule",
    "JurisdictionGroupFromAcceptancePolicyProfile",
    "JurisdictionGroupFromAcceptancePolicyRule",
    "KeepMode",
    "Keyword",
    "KeywordTargetsAddItem",
    "KeywordTargetsRemoveItem",
    "ListCreativeFormatsRequest",
    "ListCreativeFormatsResponse",
    "ListProductsRequest",
    "ListProductsResponse",
    "ListProductsResponse1",
    "ListProductsResponse2",
    "LogEventRequest",
    "LogEventResponse",
    "LogEventResponse1",
    "LogEventResponse2",
    "Loss",
    "Losses",
    "MatchBreakdown",
    "MaxSpend",
    "MediaBuy",
    "MediaBuyChangeTerm",
    "MediaBuyChangeTermConstraints",
    "MediaBuyChangeTermConstraints1",
    "MediaBuyChangeTermConstraints2",
    "MediaBuyChangeTermConstraints3",
    "MediaBuyChangeTermConstraints4",
    "MediaBuyCommitmentResponse",
    "MediaBuyCommitmentResponse1",
    "MediaBuyCommitmentResponse2",
    "MediaBuyCommitmentResponse3",
    "MediaBuyDeliveryFromGetMediaBuyDeliveryResponse",
    "MediaBuyDeliveryFromMediaBuyDeliveryWebhookResult",
    "MediaBuyDeliveryWebhookResult",
    "MinSpendTarget",
    "Mode",
    "Money",
    "NegativeKeywordsAddItem",
    "NegativeKeywordsRemoveItem",
    "NotificationTypeFromGetMediaBuyDeliveryResponse",
    "NotificationTypeFromMediaBuyDeliveryWebhookResult",
    "ObligationCounts",
    "OpportunityFromAcceptProposalRequest",
    "OpportunityFromBuyProductsRequest",
    "OpportunityFromCreateMediaBuyRequest",
    "OpportunityFromRequestProposalsRequest",
    "OptimizationGoals",
    "OutcomeFromDeclineProposalsResponse",
    "OutcomeFromListProductsResponse",
    "OutcomeFromRefineProposalsResponse",
    "OutcomeFromRequestProposalsResponse",
    "OutcomeTarget",
    "Pacing",
    "Package",
    "PackageControl",
    "PackageRequest",
    "PackageUpdate",
    "PartialFailure",
    "PerLeaf",
    "PerformanceStandards",
    "Period",
    "Placement",
    "PolicyIdFromAcceptancePolicyRule",
    "PolicyIdFromProductDiscoveryCriteria",
    "PolicyRef",
    "Preview",
    "Preview2",
    "Preview3",
    "Preview4",
    "PreviewInput",
    "Pricing",
    "PricingOptionId",
    "ProductDiscoveryCriteria",
    "ProductDiscoveryTargetingResolution",
    "ProductIdFromProductDiscoveryCriteria",
    "ProductIdFromProductPurchase",
    "ProductIdFromRequestProposalsResponse",
    "ProductPurchase",
    "ProductPurchaseInput",
    "ProductRefinementRequests",
    "ProductRefinementRequests1",
    "ProductRefinementRequests2",
    "ProductRefinementRequests3",
    "ProductRefinementRequests4",
    "ProductResponseField",
    "ProductResponseFields",
    "Proposal2",
    "Proposal3",
    "Proposal4",
    "Proposal5",
    "Proposal6",
    "ProposalBudgetConstraint",
    "ProposalDecline",
    "ProposalFromRefineProposalsResponse",
    "ProposalFromRequestProposalsResponse",
    "ProposalKind",
    "ProposalRefinement",
    "ProposalRefinement2",
    "ProposalRefinement3",
    "ProposalRefinement4",
    "ProposalRefinement5",
    "ProposalRefinement6",
    "ProposalRefinement7",
    "ProposalRefinement8",
    "ProposalRefinement9",
    "ProposalStatusFromAcceptProposalResponse",
    "ProposalStatusFromBuyProductsResponse",
    "ProposalStatusFromGetMediaBuysResponse",
    "ProposalStatusFromMediaBuyCommitmentResponse",
    "ProposalStatusFromRefineProposalsResponse",
    "ProposalStatusFromRequestProposalsResponse",
    "ProvidePerformanceFeedbackRequest",
    "ProvidePerformanceFeedbackResponse",
    "ProvidePerformanceFeedbackResponse1",
    "ProvidePerformanceFeedbackResponse2",
    "PurchaseBindingFromAcceptProposalResponse",
    "PurchaseBindingFromBuyProductsResponse",
    "PurchaseBindingFromMediaBuyCommitmentResponse",
    "PurchaseContinuation",
    "PurchaseContinuation1",
    "PurchaseContinuation2",
    "PurchaseContinuation3",
    "PurchaseContinuation4",
    "PurchaseContinuation5",
    "PurchaseContinuation6",
    "PurchaseContinuation7",
    "Qualifier",
    "ReasonFromBuildCreativeAsyncResponseInputRequired",
    "ReasonFromCreateMediaBuyAsyncResponseInputRequired",
    "ReasonFromGetProductsAsyncResponseInputRequired",
    "ReasonFromSyncCatalogsAsyncResponseInputRequired",
    "ReasonFromUpdateMediaBuyAsyncResponseInputRequired",
    "Refine",
    "Refine1",
    "Refine2",
    "Refine3",
    "RefineProposalsInputRequired",
    "RefineProposalsRequest",
    "RefineProposalsResponse",
    "RefineProposalsResponse1",
    "RefineProposalsResponse2",
    "RefineProposalsSubmitted",
    "RefineProposalsWorking",
    "RefinementApplied",
    "RefinementApplied1",
    "RefinementApplied2",
    "RefinementApplied3",
    "Refinements",
    "RegionAliase",
    "RegistryAcceptancePolicyProfileReference",
    "ReportingCommitment",
    "ReportingDimensions",
    "ReportingPeriodFromGetMediaBuyDeliveryResponse",
    "ReportingPeriodFromMediaBuyDeliveryWebhookResult",
    "ReportingRevisionBinding",
    "ReportingStatusView",
    "RequestProposalsInputRequired",
    "RequestProposalsRequest",
    "RequestProposalsResponse",
    "RequestProposalsResponse1",
    "RequestProposalsResponse2",
    "RequestProposalsResponse3",
    "RequestProposalsResponse4",
    "RequestProposalsSubmitted",
    "RequestProposalsWorking",
    "Results1",
    "Results10",
    "Results11",
    "Results12",
    "Results14",
    "Results15",
    "Results16",
    "Results17",
    "Results18",
    "Results2",
    "Results20",
    "Results21",
    "Results22",
    "Results23",
    "Results26",
    "Results27",
    "Results3",
    "Results4",
    "Results5",
    "Results8",
    "Results9",
    "ResultsFromDeclineProposalsResponse",
    "ResultsFromRefineProposalsResponse",
    "ResultsFromSyncReportingReceiptsResponse",
    "ResultsFromSyncReportingStatusResponse",
    "ScopeFromAcceptancePolicyProfile",
    "ScopeFromGetProductsResponse",
    "ScopeFromGetReportingStatusResponse",
    "ScopeFromListProductsResponse",
    "ScopeFromRequestProposalsResponse",
    "SelectedProductId",
    "Semantics",
    "Setup",
    "SignalCondition",
    "SignalCondition1",
    "SignalCondition2",
    "SignalCondition3",
    "SignalCondition4",
    "SignalCondition5",
    "SignalCondition6",
    "SignalCondition7",
    "Snapshot",
    "SourceAdcpVersion",
    "SourceFromListCreativeFormatsResponse",
    "SourceFromSyncAudiencesResponse",
    "Spot",
    "StartTime",
    "StatusFilterFromGetMediaBuyDeliveryRequest",
    "StatusFilterFromGetMediaBuysRequest",
    "StatusFromAcceptProposalRequest",
    "StatusFromBuyProductsRequest",
    "StatusFromCreateMediaBuyRequest",
    "StatusFromGetMediaBuyDeliveryResponse",
    "StatusFromGetProductsResponse",
    "StatusFromGetReportingStatusResponse",
    "StatusFromMediaBuyDeliveryWebhookResult",
    "StatusFromRefineProposalsResponse",
    "StatusFromRequestProposalsRequest",
    "StatusFromRequestProposalsResponse",
    "Subject",
    "SubjectCategory",
    "SubjectFacetFromAcceptanceContext",
    "SubjectFacetFromAcceptancePolicyRule",
    "SuggestionFromGetProductsRejected",
    "SuggestionFromGetProductsResponse",
    "SuggestionFromRefineProposalsResponse",
    "SuggestionFromRequestProposalsResponse",
    "SyncAudiencesRequest",
    "SyncAudiencesResponse",
    "SyncAudiencesResponse1",
    "SyncAudiencesResponse2",
    "SyncAudiencesResponse3",
    "SyncCatalogsInputRequired",
    "SyncCatalogsRequest",
    "SyncCatalogsResponse",
    "SyncCatalogsResponse1",
    "SyncCatalogsResponse2",
    "SyncCatalogsResponse3",
    "SyncCatalogsSubmitted",
    "SyncCatalogsWorking",
    "SyncEventSourcesRequest",
    "SyncEventSourcesResponse",
    "SyncEventSourcesResponse1",
    "SyncEventSourcesResponse2",
    "SyncReportingReceiptsRequest",
    "SyncReportingReceiptsResponse",
    "SyncReportingStatusRequest",
    "SyncReportingStatusResponse",
    "Tag",
    "TargetCapabilityId",
    "TotalBudgetFromAcceptProposalRequest",
    "TotalBudgetFromBuyProductsRequest",
    "TotalBudgetFromCommercialTerms",
    "TotalBudgetFromControlMediaBuyRequest",
    "TotalBudgetFromCreateMediaBuyRequest",
    "TotalBudgetFromUpdateMediaBuyRequest",
    "TotalBudgetGuidance",
    "TotalsFromGetMediaBuyDeliveryResponse",
    "TotalsFromMediaBuyDeliveryWebhookResult",
    "UnsatisfiedConstraint",
    "UpdateMediaBuyInputRequired",
    "UpdateMediaBuyRequest",
    "UpdateMediaBuyResponse",
    "UpdateMediaBuyResponse1",
    "UpdateMediaBuyResponse2",
    "UpdateMediaBuyResponse3",
    "UpdateMediaBuySubmitted",
    "UpdateMediaBuyWorking",
    "ValueCurrency",
    "Variant",
    "VariantAxis",
    "WarningFromAcceptProposalResponse",
    "WarningFromBuyProductsResponse",
    "WarningFromControlMediaBuyResponse",
    "WarningFromMediaBuyCommitmentResponse",
    "Window",
]
