# generated by datamodel-codegen:
#   filename:  media_buy/sync_reporting_status_request.json
#   timestamp: 2026-10-04T15:01:24+00:00

from __future__ import annotations

from adcp.types.base import AdcpRequest

from typing import Annotated

from pydantic import ConfigDict, Field

from ..core import canonical_account_ref
from ..core import context as context_1
from ..core import ext as ext_1
from ..core import reporting_consumer_status
from ..core.version_envelope import AdcpVersionEnvelope


class SyncReportingStatusRequest(AdcpRequest, AdcpVersionEnvelope):
    model_config = ConfigDict(
        extra='forbid',
    )
    account: canonical_account_ref.CanonicalAccountReference
    idempotency_key: Annotated[
        str,
        Field(
            description='Client-generated batch key. Exact retries reuse the key and body.',
            max_length=255,
            min_length=16,
            pattern='^[A-Za-z0-9_.:-]{16,255}$',
        ),
    ]
    statuses: Annotated[
        list[reporting_consumer_status.ReportingConsumerStatus],
        Field(
            description='Immutable status updates. New state uses a new reporting_status_id and explicitly supersedes the current status for that expected period. A batch contains at most one update for each logical status chain. content_mismatch entries report a consumed revision that contradicts the accepted configuration generation; they are operational disagreements about contract facts, never measurement disputes.',
            max_length=100,
            min_length=1,
        ),
    ]
    context: context_1.ContextObject | None = None
    ext: ext_1.ExtensionObject | None = None
