# generated by datamodel-codegen:
#   filename:  core/assets/brief_asset.json
#   timestamp: 2026-04-16T02:55:59+00:00

from __future__ import annotations

from ..creative_brief import CreativeBrief

BriefAsset = CreativeBrief
