# generated by datamodel-codegen:
#   filename:  core/assets/brief_asset.json
#   timestamp: 2026-04-18T19:31:26+00:00

from __future__ import annotations

from ..creative_brief import CreativeBrief


class BriefAsset(CreativeBrief):
    pass
