# generated by datamodel-codegen:
#   filename:  core/assets/catalog_asset.json
#   timestamp: 2026-04-18T19:31:26+00:00

from __future__ import annotations

from ..catalog import Catalog


class CatalogAsset(Catalog):
    pass
