# generated by datamodel-codegen:
#   filename:  brand/acquire_rights_request.json
#   timestamp: 2026-03-16T00:33:16+00:00

from __future__ import annotations

from datetime import date as date_aliased
from typing import Annotated

from adcp.types.base import AdCPBaseModel
from pydantic import ConfigDict, Field, RootModel

from ..core import brand_ref
from ..core import context as context_1
from ..core import ext as ext_1
from ..core import format_id
from ..core import push_notification_config as push_notification_config_1
from ..enums import right_use


class Country(RootModel[str]):
    root: Annotated[str, Field(pattern='^[A-Z]{2}$')]


class Campaign(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    description: Annotated[str, Field(description='Description of how the rights will be used')]
    uses: Annotated[
        list[right_use.RightUse],
        Field(description='Specific rights uses for this campaign', min_length=1),
    ]
    countries: Annotated[
        list[Country] | None,
        Field(description='Countries where the campaign will run (ISO 3166-1 alpha-2)'),
    ] = None
    format_ids: Annotated[
        list[format_id.FormatId] | None, Field(description='Creative formats that will be produced')
    ] = None
    estimated_impressions: Annotated[
        int | None, Field(description='Estimated total impressions for the campaign', ge=0)
    ] = None
    start_date: Annotated[
        date_aliased | None, Field(description='Campaign start date (ISO 8601)')
    ] = None
    end_date: Annotated[date_aliased | None, Field(description='Campaign end date (ISO 8601)')] = (
        None
    )


class AcquireRightsRequest(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    rights_id: Annotated[
        str, Field(description='Rights offering identifier from get_rights response')
    ]
    pricing_option_id: Annotated[
        str, Field(description='Selected pricing option from the rights offering')
    ]
    buyer: Annotated[brand_ref.BrandReference, Field(description="The buyer's brand identity")]
    campaign: Annotated[Campaign, Field(description='Campaign details for rights clearance')]
    revocation_webhook: Annotated[
        push_notification_config_1.PushNotificationConfig,
        Field(
            description='Webhook for rights revocation notifications. If the rights holder needs to revoke rights (talent scandal, contract violation, etc.), they POST a revocation-notification to this URL. The buyer is responsible for stopping creative delivery upon receipt.'
        ),
    ]
    push_notification_config: Annotated[
        push_notification_config_1.PushNotificationConfig | None,
        Field(
            description='Webhook for async status updates if the acquisition requires approval. The rights agent sends a webhook notification when the status transitions to acquired or rejected.'
        ),
    ] = None
    idempotency_key: Annotated[
        str | None,
        Field(
            description='Client-generated key for safe retries. Resubmitting with the same key returns the original response rather than creating a duplicate acquisition.',
            max_length=255,
            min_length=8,
        ),
    ] = None
    context: context_1.ContextObject | None = None
    ext: ext_1.ExtensionObject | None = None
