# generated by datamodel-codegen:
#   filename:  brand/creative_approval_request.json
#   timestamp: 2026-03-16T00:33:16+00:00

from __future__ import annotations

from typing import Annotated, Any

from adcp.types.base import AdCPBaseModel
from pydantic import AnyUrl, ConfigDict, Field

from ..core import context as context_1
from ..core import ext as ext_1
from ..core import format_id


class CreativeApprovalRequest(AdCPBaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    rights_id: Annotated[str, Field(description='Rights grant this creative was produced under')]
    creative_id: Annotated[
        str | None,
        Field(
            description='Buyer-assigned creative identifier. Equivalent to OpenRTB crid. Used to track approval status across resubmissions.'
        ),
    ] = None
    creative_url: Annotated[
        AnyUrl, Field(description='URL where the creative asset can be retrieved for review')
    ]
    creative_format: Annotated[
        format_id.FormatId | None, Field(description='Format of the creative being submitted')
    ] = None
    description: Annotated[
        str | None, Field(description='Description of the creative for reviewer context')
    ] = None
    metadata: Annotated[
        dict[str, Any] | None,
        Field(
            description='Additional creative metadata (duration, dimensions, target audience, etc.)'
        ),
    ] = None
    idempotency_key: Annotated[
        str | None,
        Field(
            description='Client-generated key for safe retries. Resubmitting with the same key returns the original response.',
            max_length=255,
            min_length=8,
        ),
    ] = None
    context: context_1.ContextObject | None = None
    ext: ext_1.ExtensionObject | None = None
